### ISSUE TITLE
Calendar-carousel 

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/woll-forum#103]
<img width="1435" alt="スクリーンショット 2021-04-12 15 17 14" src="https://user-images.githubusercontent.com/61481039/114348956-3ae49c00-9ba2-11eb-9ac5-a7d5594cfc05.png">

This is the top screen of pediatric asthma, but I have some questions.
Location: Pediatric Asthma　Layout　Dashboard

```
"classes": {
    "root": "my-2"
  },
```

`"condition": "props.count> 0",
`
```
"connect": [
    {
      "title": "top",
      "source": "top",
      "pick": "1",
      "apply": "sum ( ls) ""
    }
  ]
```
I don't know how these three points work, and I haven't created one, so could you please tell me?

**Comment by Show-M** [comment]
`"condition": "props.count> 0",`
It means "when there are more than 1 entry made by user"
<Br>
`"connect": [
    {
      "title": "top",
      "source": "top",
      "pick": "1",
      "apply": "sum ( ls) ""
    }
  ]`
It means "Pulling entries made on TOP tracker and counting each entry as 1 and the system sums up like 1+1+1+1+..."

@rgagne  Correct or add comment please.

**Comment by shunyaogawa** [comment]
I have an additional question, could you please tell me how to link the calendar carousel and tracker?

**Comment by rgagne** [comment]
yes, that's correct

**Comment by Show-M** [comment]
@rgagne 
Can you add an answer on this ? 
```
"classes": {
    "root": "my-2"
  },
```
