### ISSUE TITLE
Order difference of Wiki contents on wiki admin look & Actual screen

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#110]
# Sort order

Currently wiki children are displayed alphabetically. We'd like to sort either alphabetically or via sort order that is manually set.

## Requirements

1. sortChildren and sortOrder are available in the API
2. sortChildren can be `alphabetical` | `ordered` with the default being alphabetical; sort children is set on the parent node
3. If sortChildren is set to ordered then it should be set to a value in admin
4. Show sorted result in admin
5. Show sorted result in wiki child widget shown to users
6. Allow drag and drop reordering in admin when sortChildren is set to `ordered` (make sure this is implemented in as a plugin to the current tree widget)

## Current behavior

<img width="400" alt="スクリーンショット 2021-04-25 18 28 02" src="https://user-images.githubusercontent.com/61481039/115988585-6a10f980-a5f5-11eb-82c8-b9c80ba52464.png">
<img width="400" alt="スクリーンショット 2021-04-25 18 28 10" src="https://user-images.githubusercontent.com/61481039/115988587-6b422680-a5f5-11eb-91d6-6e9508bfcd07.png">
<img width="400" alt="スクリーンショット 2021-04-25 18 37 35" src="https://user-images.githubusercontent.com/61481039/115988590-6c735380-a5f5-11eb-85bf-88c1e308296b.png">

**Comment by rgagne** [comment]
@Show-M - note that the current behavior is alphabetical; a quick fix is simply to put a number at the start of the title.. that will sort it.

**Comment by hiccup1991** [comment]
@rgagne 

`sortChildren and sortOrder are available in the API`
where are sortChildren and sortOrder?
what does API mean?


`Allow drag and drop reordering in admin when sortChildren is set to ordered (make sure this is implemented in as a plugin to the current tree widget)`
Looks like this is a new feature, not a bug.

**Comment by rgagne** [comment]
sortChildren and sortOrder are available in the API = in the GraphQL interface
None of this is a bug
