### ISSUE TITLE
Table function on wiki contents

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#111]
Can we support it on wiki contents?

小児で主に用いられる長期管理薬、発作治療薬 | 名称 | 特徴
-- | -- | --
長期管理薬 | １　吸入ステロイド薬 | 長期管理薬の中心的な薬。気道の抗炎症効果が一番強い。
長期管理薬 | ２　吸入ステロイド薬・長時間作用性β2刺激薬配合剤 | 2種の薬の相互作用により治療効果増強   5歳以上で使用
長期管理薬 | ３　ロイコトリエン受容体拮抗薬 | 気管支拡張、気道炎症抑制、運動誘発ぜん息の抑制効果あり
長期管理薬 | ４　その他抗アレルギー薬   （Th2サイトカイン阻害薬・クロモグリク酸ナトリウムなど） | 化学伝達物質遊離抑制作用などにより発作の予防効果あり
長期管理薬 | ５　テオフィリン徐放製剤 | 気管支拡張、線毛運動の促進などの効果あり、有効安全域狭いため血中濃度モニタリングが必要
長期管理薬 | ６　生物学的製剤 | 主に重症ぜん息治療に使用する皮下注射薬。高価だが小児慢性特疾病医療費助成の対象となっている
発作治療薬 | １　短時間作用型β2刺激薬 | 特に吸入薬は即効性があり有効。家庭で使用する場合は回数・量の確認を。
発作治療薬 | ２　全身性ステロイド薬 | 効果発現まで時間がかかり家庭での発作治療薬には適さない。
発作治療薬 | ３　テオフィリン薬 | 効果発現まで時間がかかり家庭での発作治療薬には適さない。

**Comment by rgagne** [comment]
We're introducing Markdown as a format to replace HTML; this will support tables

**Comment by rgagne** [comment]
This is now supported
