### ISSUE TITLE
calendar carousel photo

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/woll-forum#115]
![panda-iro](https://user-images.githubusercontent.com/78076746/116652115-7adbb980-a9bf-11eb-8bd2-a48fb868b84a.png)
![topurl](https://user-images.githubusercontent.com/78076746/116652116-7b745000-a9bf-11eb-9984-01f5ac7a6d30.png)
![top](https://user-images.githubusercontent.com/78076746/116652124-80390400-a9bf-11eb-88bb-b1eb4ab352ca.png)

I'm thinking of using my own photo as a background in calendar carousel. What should I do?
The image to be used is an image of a panda with a pink background.

**Comment by Show-M** [comment]
@rgagne 
i think what we need to do here is following. Can you check?

1. Upload the file. 
<img width="525" alt="スクリーンショット 2021-05-05 14 22 54" src="https://user-images.githubusercontent.com/61481039/117099976-83f8cc00-adad-11eb-8c1b-3a2f4218535d.png">

2. Copy & paste the entire amazonaws.com URL to value
```
"target": "calendar-carousel",
      "icon": "fad fa-home-lg-alt",
      "options": {
        "rules": [  
          {
            "condition": "date(values.date) is today",
            "path": "root.backgroundImage",
            "value": "url(https://photos.google.com/photo/AF1QipPX5UOcSCGRtWVDCgD5VsmnTXC-NBgvvyRvUJYA)"
          }
        ],
```

**Comment by shunyaogawa** [comment]
![situmonpic](https://user-images.githubusercontent.com/78076746/118353349-cb970900-b5a0-11eb-87f6-cb6dc50694cb.png)
![situmonpic2](https://user-images.githubusercontent.com/78076746/118353358-cfc32680-b5a0-11eb-8688-5982bd3eac2d.png)

I added a file, put in two types of code and tried it, but it didn't show up.
Is there anything I'm doing wrong?

**Comment by Show-M** [comment]
@shunyaogawa 
I modified as below. Now you can see it.
```
{
        "condition": "date(values.date) is today",
        "path": "root.backgroundImage",
        "value": "url(https://weave-io-files.s3.amazonaws.com/files/org/b5c663b7-d9ab-4aaa-80d8-19be10ce9787/Z5lHhcdp62SdFRMXcmYaryV8LGnEXBc2e724d0207741bb846b54e9a941bdc2/panda-iro.png)"
      }
```

You need to copy& paste the file URL by right clicking here.
<img width="664" alt="スクリーンショット 2021-05-15 21 25 33" src="https://user-images.githubusercontent.com/61481039/118360969-2726be00-b5c4-11eb-9502-d59d09721eae.png">
