### ISSUE TITLE
Automation of Data Process for Med Page every few months...

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#120]
There are 2 zip.files.
https://drive.google.com/file/d/1dtz66ROIdLGa1O_rlDBQnIeI7oU8wMEl/view?usp=sharing
https://drive.google.com/file/d/1sgjdikiJwlBQKKbVI-W7Dwue4UzlRmEG/view?usp=sharing
Both contain identical set of data. But data-format is different. We can use one of them
xml_02_all.zip contains 2 type of data format(old-new)
xml_19_all.zip contains only 1 type of data format(old)
<br>
You will combine all the individual xml files, then convert.
<br>
<br>
<br>
### Data Process 1

First, please make list of data containing path below.
As an example, what we need are:
- Med given number: 874300
- Med Name: テクネゾール
- Dosage: 注射

- Med given number: it will be used only in order to sort our meds related to asthma. It will not be displayed on app.
-  Dosage:  we need only the last part. "注射” was for this med. It can be different words depending on meds.

`<sccjno en="日本標準商品分類番号" label="日本標準商品分類番号">874300</sccjno>`

```
<lst.t dsp="off">
<srl.t>
<dtl.t>
【色】
<br/>
無色澄明
<br/>
【剤形】
<br/>
水性注射剤／液剤／注射
</dtl.t>
</srl.t>
```

`<brand.name en="販売名和名">テクネゾール</brand.name>`
<br>
<br>
<br>
### Data Process 2

once we have all the selected data set,
We will keep medicine data containing one of these numbers (87221,87222,87223,87224,87225,87226,87229 and 87449)
These will be the data we need for asthma project. Everything else we cut off.

* Last number in the example,"875200"   0 is not important. **we need to look at first 5 numbers**.
* But for example, if the number was "872265", then we can see that it is asthma med as it contains "87226"

i.g)

```
{
        "name": "ツムラ竹じょ温胆湯エキス顆粒（医療用）",
        "jsn": "875200",
        "dosage": "内用"
 },
```
<br>
<br>
<br>

### Data Process 3

Every "name" containing the word, "吸入" should change its dosage into "吸入"
i.g

```
{
        "name": "シーブリ吸入用カプセル50μg",
        "jsn": "872259",
        "dosage": "外用"
 },
```
<br>
In every "name" delete the part,"「＊＊＊」" . ＊＊＊ can be different words.
i.g
Delete "「三恵」" part in this case including "「」"

```
     {
        "name": "dl−メチルエフェドリン塩酸塩散10％「三恵」",
        "jsn": "872221",
        "dosage": "内用"
    },
```
<br>
When you delete all the "「＊＊＊」", you will find exact same "name"s a lot. Delete all of duplications and leave just one.
i.g
When you delete "「＊＊＊」" part, all 3 below has the same name"dl−メチルエフェドリン塩酸塩散10％".
We keep only 1 of 3. Rests must be removed

```
{
        "name": "dl−メチルエフェドリン塩酸塩散10％「メタル」",
        "jsn": "872221",
        "dosage": "内用"
    },
    {
        "name": "dl−メチルエフェドリン塩酸塩散10％「三恵」",
        "jsn": "872221",
        "dosage": "内用"
    },
    {
        "name": "dl−メチルエフェドリン塩酸塩散10％「マルイシ」",
        "jsn": "872221",
        "dosage": "内用"
    },
```

**Comment by Show-M** [comment]
Please let me check the final file before replacing with old one.

**Comment by Show-M** [comment]
### Additional process

割線→内用　
```
{
        "name": "プランルカスト錠225mg",
        "jsn": "87449",
        "dosage": "割線"
},

```

徐放性製剤→内用
```
    {
        "name": "テオフィリン徐放カプセル100mg",
        "jsn": "872251",
        "dosage": "徐放性製剤"
    },
```

**Comment by Show-M** [comment]
@rgagne 
This is done for this time.  I am not sure how the automation was created. 
You may check with @sarikabhimre18

**Comment by Show-M** [comment]
@sarikabhimre18  any news on this?

**Comment by sarikabhimre18** [comment]
@Show-M What we want to do here ?.I remember for this previously generated a data.

**Comment by Show-M** [comment]
I think if you manage to create an automation and can run whenever you need every few months, This is considered to be fixed.

**Comment by Show-M** [comment]
@sarikabhimre18 
I just realize that there is no data with dosage: 吸入. 
Did you perhaps miss it? 
It is this part I RQed.
<img width="829" alt="スクリーンショット 2021-07-14 13 56 39" src="https://user-images.githubusercontent.com/61481039/125563755-9e474757-974f-4e61-88da-d7ebdb6f14ba.png">

**Comment by sarikabhimre18** [comment]
@Show-M it was fixed previously but take a look.

**Comment by sarikabhimre18** [comment]
@Show-M it look like the description is change for Data Process 2 ?

**Comment by sarikabhimre18** [comment]
@Show-M it look like the description is changed for Data Process 2 ?

**Comment by sarikabhimre18** [comment]
@Show-M it look like the description is changed for Data Process 2 ?

**Comment by Show-M** [comment]
No, it was not changed..
And I am talking about Data process 3, not 2. 

Can you kindly run to change dosage to 吸引 on Data process 3 and re-upload the file?

**Comment by sarikabhimre18** [comment]
Uploading a file for data process 3

**Comment by Show-M** [comment]
I checked.  I believe that changed dosage to 吸引 for proper meds. 

It is good to be uploaded to weave. Can you kindly do? 
Then fix label + close this ticket plz :)
