### ISSUE TITLE
Laggy screen of Calendar carousel

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#126]
The problem is that the view breaks when scrolling forward or past the initial set of cards.

[lagging.zip](https://github.com/weaveio/WOLL-General-forum/files/6543078/lagging.zip)

![1](https://user-images.githubusercontent.com/61481039/119584445-82964e80-be03-11eb-9163-fde46a730355.gif)

**Comment by rgagne** [comment]
need more information

Where is this from? What model phone? etc.

**Comment by Show-M** [comment]
![IMG_B4B8332D8751-1](https://user-images.githubusercontent.com/61481039/119920419-48fe4880-bfa7-11eb-9f08-6050567a2e9f.jpeg)

**Comment by rgagne** [comment]
try latest build to see if there are any improvements

**Comment by Show-M** [comment]
on ver. 3.0.2636, it is not fixed..

**Comment by rgagne** [comment]
The original description is wrong. The problem is not "laggy" but rather you can't scroll past the existing days otherwise the view breaks. Laggy suggests a performance issue but actually the problem is just the view breaks.

I've disabled scrolling past a couple days in the current build .. unlikely anyway and the user can go to the calendar .. and we'll fix it.

**Comment by sarikabhimre18** [comment]
@rgagne @Show-M 
Is their issue of slow card is scrolling ?. Will not get when UI is break the below GIF represent the current scenario in my side after enabled the code which is disabled.
![weMORI (12)](https://user-images.githubusercontent.com/29194144/120651429-64cc8780-c49c-11eb-9da8-87af824b4c7c.gif)

**Comment by sarikabhimre18** [comment]
@rgagne 
I'm unable to reproduce it but as debug the code something wrong there will fix it.Here is the current scenario please review and let me know if have any changes. 
![weMORI (14)](https://user-images.githubusercontent.com/29194144/120806295-5053c200-c564-11eb-901b-cfaea80c2275.gif)
