### ISSUE TITLE
Data display of date & time when users make data entries

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#135]
医師モードで、アプリ使用者がデータを入力した時間が分かればいいなと思います。
1日の終わりに一気に入力しているのか、その都度入力しているのか、２-３日まとめて入力しているのか、1週間まとめて入力しているのか、などが分かると、アプリ入力の傾向とうつ症状が相関したり、復職の成功度合いが違ったり、など意外な発見があるかも知れません。

On doctor mode, we would like to know the time when the app user entered the data.
If we can know whether users are making entries at the end of each the day, each time, every 2-3 days, every weekend, etc, it may find something unexpected, such as a correlation between propensity and depressive symptoms, or a different degree of success in returning to work.

**Comment by rgagne** [comment]
there is both createdAt and updatedAt attached to each dispatch
