### ISSUE TITLE
Automatically provide  feedback(templete) based on score given by regular questionnaire(every 2 weeks)

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#146]
Ask patients to answer questions on a regular basis about once every one or two weeks, such as depression and anxiety.
It would be nice to have a system that give feedback according to the results.

Feedback: A form that displays a fixed phrase from the calculated total score.
Score: For example, in the evaluation of depression, 10 questions are evaluated on a 5-point scale, a total of 10-50 points are calculated, and depending on the score, "I am in a mild depression state" is displayed and feedback is considered.

```
１、2週間に一回程度でうつ病や不安などの質問紙回答を定期的に促し、質問に答えていただく。
その結果をフィードバックするシステムがあるといいです。

フィードバック: 計算した合計点数などから定型文を表示する形
点数：例えばうつの評価などで質問10個に５段階評価してもらい合計10-50点を算出、点数によって「軽い抑うつ状態です」など表示してフィードバックする事を考えている
```

**2週間に一回（休職後に１回目、以降２週間おき、最終は復職前日）添付の質問紙(PHQ-9,GAD-7）に答えて頂く**形にしたいと思っています。

[GAD-7.docx](https://github.com/weaveio/woll-forum/files/6698336/GAD-7.docx)
[PHQ-9.docx](https://github.com/weaveio/woll-forum/files/6698337/PHQ-9.docx)

**Comment by Show-M** [comment]
@rgagne 
Any thoughts on this?

**Comment by rgagne** [comment]
You can use inbox; set up a script that creates a new entry every week or every two weeks with the appropriate questions.

**Comment by Show-M** [comment]
can we send tracker using inbox too?

And droplet can not be used, i believe as the questionnaires are simple selection-format, therefore I think we need to use tracker to capture data.

**Comment by Show-M** [comment]
`regular-questionnaire-2`

**Comment by Show-M** [comment]
Does "compute" work before hitting SUBMIT? 
<img width="1437" alt="スクリーンショット 2021-07-01 22 05 16" src="https://user-images.githubusercontent.com/61481039/124129211-88451b00-dab8-11eb-9409-4346481630b8.png">

**Comment by Show-M** [comment]
@rgagne 
When i run `given tracker[regular-questionnaire-2]`, it does not display anything as a dispatch..
This happens when i add "compute" metrix on the tracker.
I can not tell what is wrong with the tracker....
<img width="1440" alt="スクリーンショット 2021-07-05 13 58 18" src="https://user-images.githubusercontent.com/61481039/124419889-5cb48000-dd99-11eb-8304-898ce6138015.png">
<img width="1430" alt="スクリーンショット 2021-07-05 13 58 48" src="https://user-images.githubusercontent.com/61481039/124419841-473f5600-dd99-11eb-9589-67143ad3c6b7.png">

**Comment by Show-M** [comment]
Evaluation:

PHQ（0-3×9問）
0-9　抑うつ傾向は認めませんでした。
10-14　抑うつ傾向を認めます。
15-19　中程度の抑うつ傾向を認めます。
20-　強い抑うつ傾向を認めます。主治医や保健師への相談をお勧めします。

GAD-7
0-9　不安傾向は認めませんでした
10-　 不安が強い状態です

**Comment by Show-M** [comment]
Next step is:
- When to display the feedback
- Create a trigger 
- Where to display the dispatch

**Comment by Show-M** [comment]
#162 should be solved first.
