### ISSUE TITLE
Why does peakflow calculate as 251.2000000000000002 ?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#147]
As I see the layout, such an outcome should not appear when 314.0 is the highest number of all time.
It looks like this weird outcome appears only on  `{store.topAllTime * .8}`
*I added only 1 entry in top tracker.
![IMG_0334](https://user-images.githubusercontent.com/61481039/120892831-0691d700-c64b-11eb-83d8-f2f527a8cdff.PNG)
![IMG_0335](https://user-images.githubusercontent.com/61481039/120892835-0abdf480-c64b-11eb-842a-3c1892c09204.PNG)
![IMG_0336](https://user-images.githubusercontent.com/61481039/120892837-0bef2180-c64b-11eb-9f52-68f292a43b33.PNG)

**Comment by Show-M** [comment]
@rgagne  
I guess this is fixed?  
If yes, plz add `Fixed `

**Comment by rgagne** [comment]
it requires a filter on the template to format the number in the layout: `{store.topAllTime * .8|numeral:0,0}`

I have added it everywhere I think it is needed. Docs are here https://docs.fluxweave.com/Configuration/Reference/Templates/
