### ISSUE TITLE
graph　figure

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/woll-forum#149]
In the graph display, it used to be displayed without any problems, but recently the numbers have not been reflected.
I didn't rewrite the program, and I searched for something strange, but I can't find it, so can you tell me?

お肌手帳→layout→かゆみグラフ

![１](https://user-images.githubusercontent.com/78076746/121096282-df92fb00-c82c-11eb-8000-3bdc9dd811d5.png)
![２](https://user-images.githubusercontent.com/78076746/121096289-e3268200-c82c-11eb-9e03-e7a105e40de1.png)

**Comment by Show-M** [comment]
It should be fixed. Can you check again?

**Comment by shunyaogawa** [comment]
When I checked it now, the correction was completed.
Thank you very much.
