### ISSUE TITLE
Why doen't entries get displayed on 1 graph but does on another graph?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#151]
`Layout: grid graph`
<img width="1418" alt="スクリーンショット 2021-06-22 18 59 23" src="https://user-images.githubusercontent.com/61481039/122905589-503d2a00-d38c-11eb-9a3e-4f9295c78d1e.png">
<br>
<br>
`Layout:  Main user profile for Dr`
<img width="1430" alt="スクリーンショット 2021-06-22 18 58 10" src="https://user-images.githubusercontent.com/61481039/122905635-59c69200-d38c-11eb-9cff-722c0529639a.png">

**Comment by rgagne** [comment]
@sarikabhimre18 can you look into this, thank you

**Comment by sarikabhimre18** [comment]
@Show-M Not getting data related to meal is their any changes in configuration by you ?
![Graph1](https://user-images.githubusercontent.com/29194144/123622446-d7c1e780-d829-11eb-9755-cc1db02efe66.png)

**Comment by Show-M** [comment]
@sarikabhimre18  
I havent added any entries recently.....you can use this person data "岩田明伽星"

**Comment by sarikabhimre18** [comment]
@Show-M I'm not able to get this 岩田明伽星 person

**Comment by sarikabhimre18** [comment]
@rgagne  as we are not getting callback method from page-search component fixed it.

**Comment by Show-M** [comment]
@sarikabhimre18 
If this is fixed with next system update, can you write so, add fix tag and move to QA ?

**Comment by sarikabhimre18** [comment]
@Show-M Yeah it's fixed i have created a PR for that if Rob Merge with master branch then get the latest changes in latest bulid.
