### ISSUE TITLE
How to add background color to graph

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#152]
Example graph location:
<img width="1418" alt="スクリーンショット 2021-06-22 19 26 21" src="https://user-images.githubusercontent.com/61481039/122909312-09513380-d390-11eb-9978-623d92183ad7.png">

Requirement:
Change background color of graph divided by 10 of y-axis.
If we can set like 0≦ red < 5, 5≦ green <10, 10≦ blue <10, that is great.
<img width="601" alt="スクリーンショット 2021-06-22 19 26 15" src="https://user-images.githubusercontent.com/61481039/122909477-3271c400-d390-11eb-9486-51c5fbb456dc.png">

**Comment by rgagne** [comment]
@sarikabhimre18 this is possible without any code changes... just feeding in the correct configuration to the chart. Please help @Show-M with the right configuration.

**Comment by sarikabhimre18** [comment]
@Show-M Want something like this ?
![c3Charts](https://user-images.githubusercontent.com/29194144/123384618-3e3cd080-d5b2-11eb-8aa6-b60030c0d619.png)

**Comment by Show-M** [comment]
@sarikabhimre18 
Exactly, but with this condition, 0≦ red < 5, 5≦ green <10, 10≦ blue <10

**Comment by sarikabhimre18** [comment]
@Show-M Yeah it's done create a PR for different color.

**Comment by Show-M** [comment]
Waiting for this function to be implemented

**Comment by Show-M** [comment]
@sarikabhimre18 
When will this be ready? 
On 3.0.2694 I still do not see the change

**Comment by sarikabhimre18** [comment]
@Show-M I will create another PR for that it look on that PR takeshi working !

**Comment by sarikabhimre18** [comment]
Merge the PR for that issue but not sure why it not working figure out for it.

**Comment by Show-M** [comment]
<img width="740" alt="スクリーンショット 2021-07-28 13 57 56" src="https://user-images.githubusercontent.com/61481039/127266182-208a4fc0-bfc1-44b1-853f-0b5137849dfe.png">
