### ISSUE TITLE
New type/way of Graph..

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#153]
I dont have a clue how we can approach to this...I would like to hear your thoughts on this, @rgagne 

## Idea
<img width="1136" alt="スクリーンショット 2021-06-22 23 03 08" src="https://user-images.githubusercontent.com/61481039/122939865-f26e0980-d3ae-11eb-8099-362f3c2df3e7.png">

## Implementation (from @rgagne )

We can achieve this by using the "table" tile that plots by day. It already supports configurable background color but will need an additional rule configuration for displaying different text for different circumstances.

<br>
<br>
Each data source:
<img width="780" alt="スクリーンショット 2021-06-22 23 14 26" src="https://user-images.githubusercontent.com/61481039/122941222-27c72700-d3b0-11eb-9fb5-2625fbe6edfd.png">
<img width="793" alt="スクリーンショット 2021-06-22 23 14 36" src="https://user-images.githubusercontent.com/61481039/122941227-285fbd80-d3b0-11eb-9e56-59aee0d6914e.png">
<img width="1430" alt="スクリーンショット 2021-06-22 23 14 57" src="https://user-images.githubusercontent.com/61481039/122941233-2a298100-d3b0-11eb-99d4-291b21bb9a6d.png">
<img width="819" alt="スクリーンショット 2021-06-22 23 15 49" src="https://user-images.githubusercontent.com/61481039/122941237-2ac21780-d3b0-11eb-8f74-e43aabeacecf.png">

**Comment by sarikabhimre18** [comment]
@Show-M from where we want to display this thing ?.

**Comment by Show-M** [comment]
here plz @sarikabhimre18 
<img width="1141" alt="スクリーンショット 2021-06-25 18 05 41" src="https://user-images.githubusercontent.com/61481039/123399885-1e240600-d5e0-11eb-9f45-01148d274147.png">

**Comment by sarikabhimre18** [comment]
@rgagne As discussion something like this ?
![asthma](https://user-images.githubusercontent.com/29194144/123408151-4f91d700-d5ca-11eb-82c9-cb3ecb3cbc22.png)

**Comment by sarikabhimre18** [comment]
@rgagne 
Here is as again review the requirements there are 4 tracker from that we only want to display a three tracker data as source and one tracker which is TOP which only used for displaying the symbol and string in the table cell. We need to add another datasource process for it ?

**Comment by Show-M** [comment]
@rgagne 
About ◎✕ table, i think we have to solve https://github.com/weaveio/woll-forum/issues/154 first before working on the table, dont we?

**Comment by Show-M** [comment]
@sarikabhimre18 
Actually Emergency Attack part is good like that. We may make it look nicer though.
Btw Can clicking table opens up appropriate entries?

**Comment by sarikabhimre18** [comment]
@Show-M `Actually Emergency Attack part is good like that. We may make it look nicer though.` yeah will work in progress for it.Yes we can open up  appropriate entries

**Comment by sarikabhimre18** [comment]
@rgagne We passing a rule which test a condition for example:- {values.status > 0 and values.status < values.goal ? '◯' : ''} rule is like this and parseConditional return values in term of either true or false. How can be get configure string using parseConditional ?

**Comment by rgagne** [comment]
@Show-M 

To build graphs we need to identify:
1. Data source - which tracker
2. Row grouping: by user? by user and by metric? Sounds like here it is by user and by medicine name
3. Column grouping: sounds like by day... but need to clarify that
4. Calculation: what value should be taken from the tracker and how should it be combined (since there may be more than one entry in a given period)
5. (New feature) additional formatting to apply to the cell (in this case the character to display)

@sarikabhimre18 the configuration should go in connect, however there are many steps missing first.

1. Group by medicine name
2. Apply based on the answers above

Current configuration
```json
"table": {
            "timeSeries": "YYYY-MM-DD; DD MMM; P1D",
            "conditionalBackground": "#000",
            "users": "current user",
            "export": "given trackers [regular-medicine]",
            "groupBy": "$user"
          },
          "connect": [
            {
              "title": "Regular medicine",
              "source": "regular_medicine",
              "pick": 2,
              "apply": "at(ls, 4)"
            }
          ]
```

Example grouping by a metric
```
"table": {
            "timeSeries": "YYYY-ww; DD-MMM-YYYY; P1W",
            "groupBy": "$user, project",
            "firstCol": 260
          },
          "connect": [
            {
              "title": "Time",
              "source": "time",
              "pick": "values.hours",
              "apply": "sum(ls)",
              "format": "0,0",
              "groupedFormat": "0,0"
            }
          ]
```

**Comment by sarikabhimre18** [comment]
@rgagne this is the current configuration
```
 {
          "tile": "table",
          "_id": "44",
          "title": "Regular Medicine",
          "condition": "true",
          "display": {
            "span": "12"
          },
          "table": {
            "timeSeries": "YYYY-MM-DD; MMM-D; P1D",
            "groupBy": "$user",
            "conditionalBackground": {
              "lightyellow, lightblack": "n <= 0",
              "lightgreen, lightblack": "n >= 1 and n < 3",
              "dodgerblue, lightblack": "n >= 3"
            }
          },
          "connect": [
            {
              "title": "Emergency Attack",
              "source": "general",
              "trackerHandle": "asthmaattack",
              "pick": "1",
              "apply": "sum(ls)",
              "format": "0,0",
              "tableData": {
                "id": 0
              }
            },
            {
              "title": "PF - 朝",
              "source": "general",
              "trackerHandle": "top",
              "pick": "1",
              "apply": "mean(ls)",
              "format": "0,0",
              "rule": "{values.status > 0 and values.status < values.goal ? '◯' : ''}",
              "tableData": {
                "id": 0
              }
            }
          ]
        }
```

**Comment by Show-M** [comment]
@rgagne 
Regarding to ◯✕◎,
I can not answer those questions you just asked here. 
Because we have to change what data to collect on #153 i belelive.

**Comment by rgagne** [comment]
@sarikabhimre18 to make the rules somewhat easier to write and process make it a list rather than a single rule. You also need to understand what pick and apply are doing. For the current implementation of table the data is reduced into each row/column combination because there could be (and usually is) more than one entry per day. This is described here https://docs.fluxweave.com/Configuration/Layout/Data/.

Pick will take a value from each dispatch (if you have pick: "1" then it is taking the number 1 rather than a value) and apply does some transformation on that list of values. That may or may not work here.. but conditional display support will at least be useful other places.

Use the configuration below. Make sure that rules are NOT processed during Render. They should run once and only once each time the data changes.

For rules have it look like:
```
"connect": [
  {
  ...
    "rules": [
      {
        "rule": "values.result > 3",
         "value": "◎"
      },
      {
        "rule": "values.result > 0",
         "value": "◯"
      },
     {
       "rule": "true",
       "value": "✕"
     }
    ]
  },
...
]

```

**Comment by sarikabhimre18** [comment]
Fixed this in latest PR.

**Comment by Show-M** [comment]
@sarikabhimre18 
just a curiosity,
Did you manage to create this without solving #154 ? 
<img width="875" alt="スクリーンショット 2021-07-07 11 46 34" src="https://user-images.githubusercontent.com/61481039/124693012-9f04cb00-df19-11eb-82da-cafd8892856e.png">

**Comment by sarikabhimre18** [comment]
@Show-M As per discussion support a conditional rule feature within an table.

**Comment by Show-M** [comment]
@rgagne 
Is Sarika's PR merged?

**Comment by Show-M** [comment]
Waiting for this function to be implemented

**Comment by Show-M** [comment]
#154 needs to be solved first then, we can apply rules using it.

**Comment by Show-M** [comment]
Once these are done, we let Drs try first. After their QA, we will implement it for patients.

**Comment by Show-M** [comment]
When #183 is solved, i probably can implement.
