### ISSUE TITLE
Create Top2 tracker for new way of capturing data

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#154]
<img width="1126" alt="スクリーンショット 2021-06-29 15 23 34" src="https://user-images.githubusercontent.com/61481039/123747511-043f3780-d8ee-11eb-8486-65fae3b69321.png">
<img width="1108" alt="スクリーンショット 2021-06-29 15 23 39" src="https://user-images.githubusercontent.com/61481039/123747525-073a2800-d8ee-11eb-9f8b-3d392292dc81.png">

Instead of capturing numbers on `number_a_day on regular-medicine tracker`,
Dr want to capture it as  Morning/Afternoon/Evening (Max 3 times) for each med.

Then compare this with `medicine metrix on top tracker`.

Note:
- We need to change and distinguish Morning/Afternoon/Evening when capturing on `number_a_day on regular-medicine tracker`
- We need to track for each med as there will be 1 graph per med
- We still evaluate ◯◎✕ of a day( `summary matrix on top tracker`). Separately, on #153 we will evaluate for each med

- How to calculate dose-rate 
e.g
Patients need to take  Morning/Evening (2 times per day)  per medicine.
But in a week the patient took 7 times in the morning  & 5 times in the evening.
In this case dose-rate for morning is 100% &  evening is 5/7 = 71.4%.
e.g.
Patients need to take  Morning/Evening (2 times per day) per medicine.
But in a month(31 days)  the patient took 31 times in the morning  & 27 times in the evening.
This means that the patients got ◎ 27 days out of 31 days. 
Therefore its monthly-dose-rate  is 27/31 = 87%

**Comment by rgagne** [comment]
Entry: this can either be a new metric on the existing tracker or 3 different trackers; fewer trackers is generally better

Not clear what the graph is supposed to do (not able to match the english description with the mockups)

1. Data source - which tracker
3. Time grouping: week, day?
4. Calculation: what value should be taken from the tracker and how should it be combined (since there may be more than one entry in a given period)

**Comment by Show-M** [comment]
looks like i better check smth with the Dr first...getting back here.

**Comment by Show-M** [comment]
looks like i better check smth with the Dr first...getting back here.

btw @sarikabhimre18 @rgagne 
Please do not implement this change to the org before making sure that the new feature works fine. 
As there are already actual users, Dr does not want users to experience any inconvienence.

**Comment by Show-M** [comment]
@sarikabhimre18 
I created a child-org, https://web.weave.io/da8484d9-80c1-4783-bc98-971457a30efb/admin/trackers  . 
Please use this one for testing and creating.

**Comment by sarikabhimre18** [comment]
@rgagne Will not sure about what we want to do here i need to create a graph ?.Can you please let me know about it.Thank you !

**Comment by Show-M** [comment]
Data source -    regular-medicine & top tracker
Time grouping: it depends. ( morning/afternoon/evening - weekly/monthly/yearly,  day(monday...sunday) - /monthly/yearly, month - yearly, 4 seasons - yearly)
Calculation: 
Instead of capturing numbers on `number_a_day on regular-medicine tracker`,
we change and capture it as Morning/Afternoon/Evening (Max 3 times).
Then compare this with `medicine metrix on top tracker`.

e.g
Patients need to take Morning/Evening (2 times per day).
But in a week the patient took 7 times in the morning & 5 times in the evening.
In this case dose-rate for morning is 100% & evening is 5/7 = 71.4%.

e.g.
Patients need to take Morning/Evening (2 times per day).
But in a month(31 days) the patient took 31 times in the morning & 27 times in the evening.
This means that the patients got ◎ 27 days out of 31 days.
Therefore its monthly-dose-rate is 27/31 = 87%

**Comment by Show-M** [comment]
@sarikabhimre18  @rgagne 
Can you guys please work on this? 
Drs are longing for this feature.

**Comment by rgagne** [comment]
waiting on the build release from apple

**Comment by Show-M** [comment]
@rgagne 
Where is it created?

**Comment by Show-M** [comment]
Once these are done, we let Drs try first. After their QA, we will implement it for patients.
