### ISSUE TITLE
how to delete tracker on schedule screen?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#156]
![image0](https://user-images.githubusercontent.com/61481039/123617850-a0136980-d842-11eb-9444-d8d7511423d2.png)

**Comment by rgagne** [comment]
It's the shortcut configuration.

**Comment by Show-M** [comment]
Right, but it means that if i change shortcut configuration , it will make changes to both on + button and the pic above. 
I want to change **only on the the part mentioned on the pic above**...
<img width="1160" alt="スクリーンショット 2021-06-29 22 12 13" src="https://user-images.githubusercontent.com/61481039/123803243-17bac480-d927-11eb-8490-aa262ef81ed9.png">

**Comment by rgagne** [comment]
Added support for context menu that can be set individually

**Comment by Show-M** [comment]
Thank you Rob.
If i want to have different trackers to each "+" on dashboard and calendar page, can we do that? 

And can you give me a quick instruction of "how & where" i can control this "context menu" ?

**Comment by Show-M** [comment]
Condition is not working 
<img width="916" alt="スクリーンショット 2021-07-12 13 25 42" src="https://user-images.githubusercontent.com/61481039/125231078-0f925a00-e315-11eb-9778-a8c000142448.png">

**Comment by Show-M** [comment]
confirmed.
