### ISSUE TITLE
What is the best way to create such a tab on user profile?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#157]
<img width="1110" alt="スクリーンショット 2021-06-28 21 57 16" src="https://user-images.githubusercontent.com/61481039/123640542-3b650880-d85c-11eb-9205-4f31ee5fe302.png">

I want to know:

1. The best way to capture date in this case
2. Good example i can look at in order to create the layout

*If we use tracker, that is the best to capture data as I will need to add some more items to be submitted by users.

**Comment by rgagne** [comment]
Everything is done with trackers; in this case create two trackers, one for pause and one for restart.

the query is `given tracker [blah], given user [$user] from past limit 1` and we'll use the content tile

**Comment by Show-M** [comment]
- Why do we need 2 trackers? Why not 2 matrix in 1 tracker??

- Why do we need query? I thought we just need to get `value.date on  loa-starting-date` and let the system calcualte..

- How can i let the system calculate how many days has passed since the loa-starting-day?

- What way should I capture the data?Considering that  I need to somehow count later how many days has passed since the loa-starting-day.
<img width="1433" alt="スクリーンショット 2021-06-29 17 18 12" src="https://user-images.githubusercontent.com/61481039/123762943-407a9400-d8fe-11eb-984f-659d9f889f32.png">

**Comment by rgagne** [comment]
1. We need two trackers, one for pause and one for restart. That way we can find them separately.
2. Everything needs a query; in this case its the query listed above to find the dispatch for pause and the other dispatch for restart. We also need to do some templates, but we have to find the dispatch first.
3. We can add date math to the template language.

How to capture depends on who will put the values into the system. If the doctor then we can do in the Web (+) if the user we can do via a dashboard or via the mobile (+).
