### ISSUE TITLE
Which tracker  connect to + button

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#159]
Calendar page:    evaluation & work-event tracker
Dashboard page:  all the activities & evaluation

*this can be done when #156 has been implemented

**Comment by rgagne** [comment]
156 has already been completed

**Comment by Show-M** [comment]
Different shortcut rule should be applied.
<img width="1286" alt="スクリーンショット 2021-07-06 12 15 19" src="https://user-images.githubusercontent.com/61481039/124536956-ea54a600-de53-11eb-9910-f2d592b65088.png">
