### ISSUE TITLE
Switch 2 mode(LOA(Leave Of Absence) / RTW(Return to work)) - different groups

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#161]
https://docs.google.com/document/d/1rNbXGRM7Ea1UUhmB_9pbaenTQn0zrKJT_hlxE0SbW_g/edit?disco=AAAAMdaYyCM
We have created mostly for LOA mode so far.

What to track on RTW;
Sleep( same as current sleep tracker)
- Time
- Quality (1-5): poor to fully rested

Work( Only type is different from current tracker)
- Type 
図書館,  リワーク, リモートワーク,  業務, 残業,出張業務
- Time

Evaluation(same as current evaluation tracker)

### note:
As it is possible that user change from LOA to RTW but come back to LOA afterwards,  2 mode should be able to switch(go forward and backward).  
We track different things on each mode.
The trigger to switch is going to be applied at the date where users make entries to `loa-return-date tracker`.

**Comment by Show-M** [comment]
maybe program function can be used?

**Comment by Show-M** [comment]
need small improvement by solving #164

**Comment by Show-M** [comment]
The trigger to move to RTW should be when `loa return date` has new input/override
The trigger to move to LOA should be when `loa starting date` has new input/override

**Comment by Show-M** [comment]
@rgagne  
Can you help me with this?

**Comment by rgagne** [comment]
Scripts created and the triggers configured

**Comment by Show-M** [comment]
I confirm these script working properly
