### ISSUE TITLE
Add Working condition and allow users to edit/view

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#163]
https://docs.google.com/document/d/1rNbXGRM7Ea1UUhmB_9pbaenTQn0zrKJT_hlxE0SbW_g/edit?disco=AAAAImz6JO0

以下よろしくお願いします。
就業上の配慮（始まったら一定期間持続し、変化するもの、複数重複あり　例：就業時間制限半日→６時間→フルタイム（就業時間制限解除＆ここまで時間外勤務禁止）→時間外勤務制限月２０時間→時間外勤務制限解除）
・就業時間制限（半日・６時間・フルタイム））
・時間外勤務（禁止・制限：月○時間まで）
・休日勤務（禁止・制限）
・交替勤務（禁止・制限）
・出張（禁止・制限）
・作業内容制限（内容：○○）

**Comment by Show-M** [comment]
`tracker: work-regulation`

**Comment by Show-M** [comment]
What is the best way to display this?

**Comment by rgagne** [comment]
dashboard is the best way to display status information

**Comment by Show-M** [comment]
@rgagne  Please set it up.
