### ISSUE TITLE
Date selection is not working properly - Affecting Eating Disorder app too

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#166]
It looks like the first date users see when they starts the app is taken over even if they change date later.
### First sceen users see: date is 12th
<img width="486" alt="スクリーンショット 2021-07-14 18 39 43" src="https://user-images.githubusercontent.com/61481039/125600932-684d8ddb-0896-4ed1-bcdb-2ce262034148.png">
### Users change date to 1st / 4th.
<img width="485" alt="スクリーンショット 2021-07-14 18 40 40" src="https://user-images.githubusercontent.com/61481039/125601079-71a18170-5d31-4171-939f-352242811e5f.png">
<img width="481" alt="スクリーンショット 2021-07-14 18 40 15" src="https://user-images.githubusercontent.com/61481039/125601082-893d26d7-0b19-46a0-b913-3a655162f70c.png">

### whatever date they choose and try to create new entries, the date is always 12th.
<img width="492" alt="スクリーンショット 2021-07-14 18 40 04" src="https://user-images.githubusercontent.com/61481039/125601142-bb7405ce-cf5e-4354-8bb3-621235a081a6.png">

Video: 
[reproduction.mp4.zip](https://github.com/weaveio/woll-forum/files/6815132/reproduction.mp4.zip)

**Comment by rgagne** [comment]
Was an incomplete implementation of the new feature.

**Comment by Show-M** [comment]
fixation is confirmed on Fluxweave, not on chant yet.
