### ISSUE TITLE
Calendar-carousel

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#173]
1. 
What is the expression for "all-time" ?
<img width="1035" alt="スクリーンショット 2021-07-20 17 31 12" src="https://user-images.githubusercontent.com/61481039/126289898-1384579a-02de-4868-8b87-e2cb1a20d697.png">

2. 
For 仕事内容, I want to have a condition of "as long as there is 1 entry all the time,  it is complete".
For ２週間おきの定期質問, I want to have a condition of "as long as there is 1 entry in last 2 weeks,  it is complete".
How and where can I set these conditions?
<img width="579" alt="スクリーンショット 2021-07-20 17 33 45" src="https://user-images.githubusercontent.com/61481039/126289501-744b475b-a4b6-4464-82b7-ee9f6ac2b15d.png">
<img width="1425" alt="スクリーンショット 2021-08-23 22 55 17" src="https://user-images.githubusercontent.com/61481039/130459715-65012ab2-d20a-49a3-b28d-e8ee876e88fe.png">

**Comment by Show-M** [comment]
this will solve #163 and #146

**Comment by rgagne** [comment]
Correct queries are:

```
current user, given trackers[work-regulation, loa-start-date, loa-return-date] from all time
current user, given tracker [regular-questionnaire] from $date to -2 weeks
```

`pros.count > 0` will be completed provided there is at least one matching item... so that seems to be correct

**Comment by Show-M** [comment]
I assume condition is not working properly.

e.g
work-regulation already has an entry. It means "props.count > 0" is true. 
But the "subtltle" and "icon do not change...

This happens to all trackers displayed on this info-board...

**Comment by Show-M** [comment]
<img width="978" alt="スクリーンショット 2021-07-28 18 04 56" src="https://user-images.githubusercontent.com/61481039/127295600-876b74f0-7817-4dca-a7ed-81f778a02e04.png">

**Comment by Show-M** [comment]
@rgagne  can you have a look please?

**Comment by rgagne** [comment]
it was missing the filter.match and therefore was matching on the current day

see
https://docs.fluxweave.com/Configuration/Layout/tiles/Tasks/

Does this need to be a date carousel? Is there a reason the user should swipe back and forth?

**Comment by Show-M** [comment]
There is no point for users to swipe back and forth. 

It looks like as a data souse **current user, given trackers[work-regulation]  from all time** does not work. 
if it is "from year" or "from month", the display of ✔ works fine.

Moreover, when i add 
```
"filter": {
        "match": "YYYY-MM-DD",
             },
```
It breaks the ✔ condition...

**Comment by Show-M** [comment]
moving to #201
