### ISSUE TITLE
New data for July

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#174]
Hi Sarika,

This is the new data for https://github.com/weaveio/woll-forum/issues/120 .

Use latest files
https://drive.google.com/drive/u/3/folders/1CifXAJgRzlBASvx0_7PgTahBDRiFVx-z

Use whichever format you prefer and process it please.
Let me know when it is done :)

**Comment by sarikabhimre18** [comment]
@Show-M 
Here is the latest converted data. Please review and let me know if have any changes. Thank you !
https://weave-io-files.s3.amazonaws.com/files/org/b15ea97f-754b-4c7f-8e8a-d8ea778385d0/yWHUB4UfCW5wRkCcQC1rsbGzGD1KDKb27aea7529eae5a527c1333626d0d183/xml19_dosageChange.json

**Comment by Show-M** [comment]
@sarikabhimre18 
ITs good to be pasted to weave system :) 

Please do so. Then plz  add fix label and move to Ready-for-QA column.
