### ISSUE TITLE
Tapping dates on calendar act as opening a context menu

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#177]
Is it possbile?

Dr thinks that now we can remove "+ button", instead, if calendar becomes tappable.

Otherwise, can we remove + button from dashboard only?  This could solve this issue too.

**Comment by rgagne** [comment]
removed; it's a setting in navigation

**Comment by Show-M** [comment]
<img width="1182" alt="スクリーンショット 2021-08-25 19 40 25" src="https://user-images.githubusercontent.com/61481039/130776469-b2a24f67-f32d-4cc3-84ef-d7f878674fa7.png">
