### ISSUE TITLE
User data  security setting 

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#178]
- 市大側が個人とデータを連係できなければ良いので、個人を特定できる情報にアクセスできてはいけない(Adminは人物特定できてもOK)
- 職員番号の割り振りは会社が行う
<br>
<br>
先生の最新コメント:

仮に、社員/職員番号が各会社から割り振られるものであれば、復職支援アプリ側が提供する招待コードを使って新規ユーザーが勝手に登録することで、本人と社員/職員番号を結び付けられるのは会社のみとなると思いますが、どうでしょうか？
→
サーバー管理者もデータを取り出して結びつけれないでしょうか？
→→
weaveとwollをサーバー管理者とする場合、これは、ユーザーがどこまでの情報を復職支援アプリに入力するかによると思います。一番シンプルなのは、ユーザーは個人名を登録しないで社員/職員番号をユーザー名とする。これだと、帰属する会社のみが社員/職員番号と本名を紐付けられます。

→→→
記録表の会社への提出時にどうしても氏名は必要ですので、氏名登録は必須です。我々だけが取り出せ無ければギリギリOKだと思います。
もう一つとしては出力・提出時に出力用として氏名を入力してもらうが、出力にのみ利用しデータベースにストアしない。というのは可能でしょうか？
<br>
<br>
記録表は誰が、どうやって作成するのか？提出方法は？
→記録表は、患者本人が手書き/Excelで作成し、直接ダイセルに提出していた。
その際に、職員番号と本名を記録表に入力/記載する必要あり。

記録表作成後に(電子/手書き)署名で問題ないのでは？
→極論、問題ない。

＊職員番号と本名のいずれも大学側は知ってはいけない。

**Comment by Show-M** [comment]
先生の最新コメント:

仮に、社員/職員番号が各会社から割り振られるものであれば、復職支援アプリ側が提供する招待コードを使って新規ユーザーが勝手に登録することで、本人と社員/職員番号を結び付けられるのは会社のみとなると思いますが、どうでしょうか？
→サーバー管理者もデータを取り出して結びつけれないでしょうか？
→→weaveとwollをサーバー管理者とする場合、これは、ユーザーがどこまでの情報を復職支援アプリに入力するかによると思います。一番シンプルなのは、ユーザーは個人名を登録しないで社員/職員番号をユーザー名とする。これだと、帰属する会社のみが社員/職員番号と本名を紐付けられます。

→→→→
記録表の会社への提出時にどうしても氏名は必要ですので、氏名登録は必須です。我々だけが取り出せ無ければギリギリOKだと思います。
もう一つとしては出力・提出時に出力用として氏名を入力してもらうが、出力にのみ利用しデータベースにストアしない。というのは可能でしょうか？

**Comment by Show-M** [comment]
記録表は誰が、どうやって作成するのか？提出方法は？
記録表作成後に(電子/手書き)署名で問題ないのでは？

**Comment by Show-M** [comment]
ダイセル is overviewing all the patients. 
Drs are there to extract data for research purpose.


Therefore 
Dr cannot know neither employment number nor real name of patients
ダイセル knows both,  employment number and real name

Patient flow to submit weekly report to ダイセル.
1. Patients export as PDF or something, 
2. They write down their employment number + real name  in the weekly report
3. They submit directly to ダイセル over email

**Comment by Show-M** [comment]
@rgagne  I would like to hear your opinion on this. Can you?

**Comment by rgagne** [comment]
If patients export as PDF, writes their information and emails.. that all takes place outside of our system and is both out of our control and also seems to meet the requirement of the doctor not knowing their name or number.

However a better workflow is for this to take place inside of the system, rather than via email which is messy, hard to track and not at all secure (the information is being sent in plain text over the Internet).

In that case the patient submits the report and we send an anonymous version to the doctor and a regular version to ダイセル.

**Comment by Show-M** [comment]
We need to give admin to Dr at some point as they should maintain later, right?
But if we give the admin authority,  admin can pull these name/number data technically...Weave can know / Dr can not.

or you sound like Weave will remain as only admin for this org? 



> In that case the patient submits the report and we send an anonymous version to the doctor and a regular version to ダイセル.

I think you meant that we can do this by writing scripts. ignore if it is correct.
