### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#180]
<img width="1419" alt="スクリーンショット 2021-08-25 21 28 51" src="https://user-images.githubusercontent.com/61481039/130790811-c5c6ef48-3f32-49f2-8a65-b6941d502622.png">
I assume that it is supposed to display "how long has it been since when user returned to work" or "how long has it been since when user left from work" ? ...like ones created here?

<img width="1276" alt="スクリーンショット 2021-08-25 21 30 26" src="https://user-images.githubusercontent.com/61481039/130790877-501b7d7d-2301-4a78-a85e-794539f28b01.png">

**Comment by rgagne** [comment]
template parsing + attached dispatch (from a query) to display time based on the dispatch date
