### ISSUE TITLE
Can you have a look on Top2 tracker?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#183]
### Issue 1.

i.g:  `given dispatch[be02679b-e713-4d05-a0c0-2bd9fd1ac1d0]`
Though patient did not take any meds, the evaluation is ○.
Its supposed to be ✗.

i.g:  `given dispatch[0b57a5c0-d186-4e65-8af1-fc86684838a3]`
another case is when patient did not take any meds, the evaluation is empty. 
Its supposed to be ✗

### Issue 2.
I added top2 tracker to display in mobile-calendar. But it displays nothing after multiple trials...
top2 should be displayed the same as original top
```
{
  "target": "calendar",
  "icon": "fad fa-calendar-week",
  "options": {
    "query": "given tracker[asthmaattack, cact, Examination-Result, top,top2], current user",
    "trackerDayFormat": {
      "cact": [
        ":icon",
        ":template"
      ],
      "Examination-Result": [
        ":template"
      ],
      "top": [
        ":template"
      ],
      "asthmaattack": [
        ":template"
      ],
      "top2": [
        ":template"
      ]
    },
    "variant": "edit"
  },
  "title": "Calendar",
  "_id": "83"
}
```

**Comment by rgagne** [comment]
issue 1 was due to a bug handling an empty list; resulted in status=1 instead of status=0; the best way to trouble shoot these is to look at the data (via the upper right menu) and see if it matches what you think it should be. I've fixed that but requires a build to work for 0 entries.

**Comment by Show-M** [comment]
let me know when its deployed.

**Comment by Show-M** [comment]
update me plz when this is checked. So that, I can move to related issues.

**Comment by Show-M** [comment]
<img width="1036" alt="スクリーンショット 2021-09-10 18 19 25" src="https://user-images.githubusercontent.com/61481039/132831484-a982d9f1-205f-4d27-adb3-09a5942a8c8d.png">

**Comment by Show-M** [comment]
fixation confirmed
