### ISSUE TITLE
◎ / ○ / ✗ table

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#184]
<img width="1136" alt="スクリーンショット 2021-06-22 23 03 08" src="https://user-images.githubusercontent.com/61481039/122939865-f26e0980-d3ae-11eb-8099-362f3c2df3e7.png">

**Comment by Show-M** [comment]
When #183 is solved, i probably can implement.

**Comment by Show-M** [comment]
@rgagne 
Can you help me with this? 

I added rule, which should work to ぜん息日記入力(Top2). Though ◎ and ○ get displayed, ✗ somehow does not.
```
        {
          "rule": "values.status is 0",
          "value": "X"
        }
```
<Br>
<br>
Location:
<img width="1439" alt="スクリーンショット 2021-09-10 18 48 44" src="https://user-images.githubusercontent.com/61481039/132835397-817b8484-0902-4f9e-8b96-7bb0077fc747.png">
<br>
<br>
Other info:
<img width="582" alt="スクリーンショット 2021-09-10 18 42 05" src="https://user-images.githubusercontent.com/61481039/132835312-90815c38-ab3b-4796-809d-e405d9a70cbb.png">
<img width="586" alt="スクリーンショット 2021-09-10 18 42 20" src="https://user-images.githubusercontent.com/61481039/132835314-c2d270b6-eb7b-47b7-b5e7-2dee0b704da8.png">
<img width="1362" alt="スクリーンショット 2021-09-10 18 44 10" src="https://user-images.githubusercontent.com/61481039/132835319-6cbe81ad-dca9-49de-9239-1431ea3ad563.png">

**Comment by sarikabhimre18** [comment]
@Show-M 
Fixed this in latest build. Please review and let me know if have any changes.

Thank you !

**Comment by rgagne** [comment]
@sarikabhimre18 sorry, wrong fix. can you roll back your code; can you also look at the comments below and update the documentation so that's clear. We already have an aggregated result, we don't need to add another way to create an aggregated result. 

@Show-M the rule is based on an aggregated result

You have:
```
"pick": "values.status",
"apply": "sum(ls)",
```

In the rules you are looking at the result of that .. called result, that may not be clear.. status is not available but you've computed it

**Comment by rgagne** [comment]
Correct configuration; pick figures out if the status is meeting goal, less than the goal or zero and provides a value matching. Apply then calculates the mean in case there is more than one. The rules then match the output of the pick/apply.

```
{
  "source": "general",
  "trackerHandle": "top2",
  "pick": "values.status >= values.goal ? 3 : (values.status > 0 ? 2 : 1)",
  "apply": "mean(ls)",
  "format": "0,0",
  "type": "dispatch",
  "rules": [
    {
      "rule": "values.result == 3",
      "value": "◎"
    },
    {
      "rule": "values.result == 2",
      "value": "◯"
    },
    {
      "rule": "values.result == 1",
      "value": "X"
    }
]
}
```

**Comment by Show-M** [comment]
"pick": "values.status == values.goal : 3, values.status == 0 : 1, values.goal > values.status > 0 : 2",

**Comment by sarikabhimre18** [comment]
@Show-M Fixed this https://github.com/weaveio/woll-forum/issues/184#issuecomment-917939097 in latest changes. Please review and let me know if have any changes.

**Comment by Show-M** [comment]
I think the latest change is good :)} Thanks!

**Comment by Show-M** [comment]
@rgagne 
Did you delete the ◎○✗ graph by accident perhaps? 
The history said that latest person who modified is you...

<img width="1153" alt="スクリーンショット 2021-09-13 19 21 32" src="https://user-images.githubusercontent.com/61481039/133067587-e9dfe75f-c641-411e-8aae-688048920d2b.png">

**Comment by rgagne** [comment]
I removed $groupBy since it was always for just one user and was creating redundant rows... in that process i updated an older version; fixed that

**Comment by Show-M** [comment]
<img width="1427" alt="スクリーンショット 2021-09-24 19 04 57" src="https://user-images.githubusercontent.com/61481039/134657374-18cf208a-cb72-410d-a237-7a06a7c51021.png">
