### ISSUE TITLE
Additional personal info to input ( it should be able to be reviewed and modified later)

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#185]
初回登録時の個人情報入力項目;
(招待コードを打ち、研究参加に同意し、復職支援ページに飛んだ後の入力で良い)
追加ですみません。個人情報、背景因子の入力画面も倫理委員会に提出することが必要です。
(氏名)、職員番号、(年齢)、(性別)、職種、職位、勤続年数、婚姻状況、最終学歴、休職期間、休職歴、休職理由、家族構成の取得を考えています。

氏名、職員番号、職種、職位: 自由記入(テキスト)

休職期間、休職歴: 数値入力
今回の休職を除いて過去に休職された期間は計何ヶ月でしょうか？
今回の休職は今回を含めて何回目でしょうか？

休職理由: 自由記入(テキスト)
休職に至った病名：休職の原因となった診断書上の病名を入力して下さい。（わからない場合は不明と入力して下さい）

家族構成: 数値入力
現在同一宅で暮らされている人数は何人でしょうか？　人
その内・２０歳未満の子供　人、介護が必要な家族　人

勤続年数：年月入力
現在の会社に入職したのはいつでしょうか？＿（年、月）
今の部署で勤務し始めたのはいつでしょうか？（年、月）

性別等: 選択式
性別: male /female/ either way 
婚姻状況：未婚、既婚
最終学歴：中学校、高校、専門学校、大学、大学院
<br>
<br>
Personal information input items at the time of initial registration;
(You can enter it after typing the invitation code, agreeing to participate in the research, and jumping to the return-to-work org)
Name
employee number
age
gender(already on initial registration)
occupation
job title
hire date
marriage status
final educational background
past leave of absence history (number of times, time, period)
leave of absence - medical certificate with disease name
medication status
fitbit loan and consent to use

**Comment by Show-M** [comment]
@rgagne  
Im thinking to create a new tracker and display it on initial registration process.  Is this the best way?

**Comment by rgagne** [comment]
Yes.. we already have support for display a tracker during initial login (after registration... but same thing)

You'd want at least 2 trackers.. one for the initial registration and one for making changes later. You would then store the data into the user's profile for easy access but the trackers provide the change over time.

**Comment by Show-M** [comment]
@rgagne 

> You'd want at least 2 trackers.. one for the initial registration and one for making changes later. You would then store the data into the user's profile for easy access but the trackers provide the change over time.

I am not catching up with this...can you explain a bit more?
