### ISSUE TITLE
Add checkbox before JOIN orgs on Chant

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#186]
In order to pass the ethical committee for Return-to-work,

It is a MUST  to have
- checkbox(☑)
- Only when user add ✓,  JOIN button works. And  Chant let users join orgs 

Can you kindly create this new feature? 
Checkbox is smth user check intentionally and hard to say that "i did not see"...according to the Dr.  I offered other way like changing text of JOIN to "I agree and continue", but got rejected.

Location &  Steps
![1](https://user-images.githubusercontent.com/61481039/131985030-01421181-6314-4f91-b27b-0d78e254c14c.gif)

It should look smth like this...this one looks ugly though.
![IMG_0403](https://user-images.githubusercontent.com/61481039/131985344-e1acb8d9-bc48-4ec2-ac04-b1f07ca98f84.PNG)

**Comment by Show-M** [comment]
Is it already deployed? I do not recognize..during the  JOIN code procedure.  
[RPReplay_Final1631527757.MP4.zip](https://github.com/weaveio/woll-forum/files/7153390/RPReplay_Final1631527757.MP4.zip)

This is one of features Dr requires for research submission to ethical committee.
So,  I would like you to check this.

**Comment by rgagne** [comment]
it's in the latest version on test flight

**Comment by rgagne** [comment]
there was an issue with the build.. there now

I accept in Japanese = 利用規約に同意します

<img src="https://user-images.githubusercontent.com/428897/133218487-bc46226a-a1be-4150-9545-48a54179a8a6.png" width="200"/>

**Comment by Show-M** [comment]
I accept in Japanese = 利用規約に同意します

That is correct. I guess i need to wait for the update with Japanese texts including "JOIN" ?

JOIN = 参加する(or 参加)
