### ISSUE TITLE
Additional process to be added to #120

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#187]
We already completed #120.

This is an additional  process.

For every `"name":` including following texts, please change their dosage to "吸入" .

List:
吸入液
エアゾール
エアー
ロタディスク
ディスカス
スイングヘラー
タービュヘイラー
インヘラー
ツイストヘラー
エリプタ
ジェヌエア
レスピマット
エアロスフィア

**Comment by sarikabhimre18** [comment]
@Show-M 
Here is process json file. Please take a look let me know if have any changes.

https://weave-io-files.s3.amazonaws.com/files/org/b15ea97f-754b-4c7f-8e8a-d8ea778385d0/kZ1eBgzWD33iRwqNYzbw41eeJx0xuP23cdab0eb9bf9ba53edc2080c4f7d468/xml19_dosageChangesLatest.json

Thank you !

**Comment by Show-M** [comment]
It looks good  :) 
Please upload to the weave.Then I believe this is done!

**Comment by sarikabhimre18** [comment]
@Show-M 
Uploaded on the weave done !
