### ISSUE TITLE
Setting wizard as intake is not giving a proper screen during first log-in process

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#189]
<img width="1407" alt="スクリーンショット 2021-09-08 18 34 47" src="https://user-images.githubusercontent.com/61481039/132485359-ddab6748-ada7-43bc-8263-b35cdc401fe5.png">

**Comment by Show-M** [comment]
@rgagne 
And this one is also related to research submission...kindly have a look :v

**Comment by rgagne** [comment]
The security was not enabled for any group... therefore it did not load. Resolved.

**Comment by rgagne** [comment]
Should these things get saved to the user profile? 
I've also enabled this in "Edit profile" ... but not sure it should go there. There probably should be a way to invoke it later just in case.

**Comment by Show-M** [comment]
invoke = recall the previous dispatch and let user modify? That is yes. 
I tried "edit profile"...apparently it is treated as a new entry.

And during first log-in process, i did not meet this screen...

**Comment by rgagne** [comment]
First log in process = the very first time you open the app as a new user; this is working (and used in lots of orgs).

Since no one will be directly logging into this org (they use a join code) then need to make some additional changes

**Comment by Show-M** [comment]
> First log in process = the very first time you open the app as a new user; this is working (and used in lots of orgs). Since no one will be directly logging into this org (they use a join code) then need to make some additional changes.

I see. Then  between "Type in JOIN code　→　Join intended org" process, the intake-wizard should be working. 
Download CHANT　→　Automatically Join WOLL　→　Type in JOIN code　→　Join intended org

> Also we don't recall the previous dispatch and let the user modify. It will always be a new entry. What it can do is save the data into the users profile and load it for later new entries (so that the values are all pre-populated).

I mean yes, that is great to have!

**Comment by Show-M** [comment]
is this ready? @rgagne
