### ISSUE TITLE
Rule is not applied on ◯✕◎ graph 

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#192]
This is working ok.
```
    "conditionalBackground": {
      "#DF5E5E, #0A1931": "n == 1",
      "#FFFFE0, #0A1931": "n == 2",
      "#B5CDA3, #0A1931": "n == 3"
    }
```

But it looks like below is not functional...Can you have a look? Probably pick is wrong? 
```
        {
          "rule": "values.result == 3",
          "value": "◎"
        },
        {
          "rule": "values.result == 2",
          "value": "◯"
        },
        {
          "rule": "values.result == 1",
          "value": "X"
        }
```
<img width="1433" alt="スクリーンショット 2021-09-17 10 47 49" src="https://user-images.githubusercontent.com/61481039/133711052-bb14418e-626e-41c8-9042-594eddef6f66.png">

**Comment by sarikabhimre18** [comment]
@Show-M is this working fine for my side. How can i reproduce it ?
![rulesa](https://user-images.githubusercontent.com/29194144/133730527-3daeeb7c-0330-4dd1-9270-476d067dcf5f.png)

**Comment by sarikabhimre18** [comment]
@Show-M @rgagne 
Also not sure about actual requirement for this one.Look at the below image i'm cloning the sho dispatches it show two different combine string.
![dataa](https://user-images.githubusercontent.com/29194144/133731779-c19f9719-2bc7-48c3-b5ee-5f0862cce83a.png)

**Comment by Show-M** [comment]
@sarikabhimre18 

> @Show-M is this working fine for my side. How can i reproduce it ?

I dont know...i have not done anything special. My version is 3.0.2764.



> Also not sure about actual requirement for this one.Look at the below image i'm cloning the sho dispatches it show two different combine string.

I tried to make some new entries for `Top2 tracker ` and it works fine with mine.
<img width="806" alt="スクリーンショット 2021-09-17 15 08 14" src="https://user-images.githubusercontent.com/61481039/133733001-68d26b1b-375e-416b-8820-5d2d87bb8e26.png">

I noticed that 
1. your `given tracker[regular-medicine-2]` does not exist.
2. Your dispatch says 
```
  "goal": 0,
  "morningGoal": 0,
  "noonGoal": 0,
  "nightGoal": 0,
```
But it should not be zero?

**Comment by sarikabhimre18** [comment]
@Show-M 
I think changes are not live yet.
The current version is 3.0.2764.

The thing work fine in development mode like https://github.com/weaveio/woll-forum/issues/192#issuecomment-921515175. Please review with latest build.
Thank you !

**Comment by Show-M** [comment]
@rgagne   @sarikabhimre18 
Please  finish uploading by 27th.

**Comment by sarikabhimre18** [comment]
@Show-M it's already done just need to a latest build for web to check on.Work on development mode !

**Comment by Show-M** [comment]
<img width="1427" alt="スクリーンショット 2021-09-24 19 04 57" src="https://user-images.githubusercontent.com/61481039/134657438-10102231-1c34-4b54-b45e-2b68ce4ccbd5.png">
