### ISSUE TITLE
data source for "tile": "tasks"

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#201]
<img width="1158" alt="スクリーンショット 2021-10-04 12 20 38" src="https://user-images.githubusercontent.com/61481039/135788203-430f502e-c4f5-4339-9f45-53ad33004219.png">

It looks like as a data souse current user, given trackers[work-regulation] from all time does not work.
if it is "from year" or "from month", the display of ✔ works fine.
Is this a correct behavior?

**Comment by Show-M** [comment]
@sarikabhimre18  can you have a look?

**Comment by sarikabhimre18** [comment]
@Show-M Setting like this one right ?

![Screenshot (72)](https://user-images.githubusercontent.com/29194144/150310581-962bf2e4-9e2d-40a0-9727-a4ae77463760.png)

Display like this one right ?
![Screenshot (73)](https://user-images.githubusercontent.com/29194144/150310746-e6eda611-722b-4815-ad47-7a4ed7476fee.png)

It will work in admin panel.
![Screenshot (74)](https://user-images.githubusercontent.com/29194144/150310833-06a94e4b-c8fd-4db1-9757-cdfc90c5924f.png)

Can you please provide bit more about requirements ?. Not sure about it .

**Comment by Show-M** [comment]
my bad. Please disregard this. It seems to be functional now :v
