### ISSUE TITLE
EXACT tracker questions must be completely filled.

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#209]
In order to achieve the condition mentioned on title, i think there are 2 approaches below.
Do we have any of those in configuration?

Note: The format has to be "wizard" styled. This is because the copyright for EXACT scoring method

I know that this, input rule exists. But it does not do the `indicate "where is not answered yet"`. So, I found it pretty inconvenient..
<img width="915" alt="スクリーンショット 2021-10-12 16 10 33" src="https://user-images.githubusercontent.com/61481039/136908842-8ebc48fc-abdc-48f9-b13a-a646404f53f1.png">

1. Users can not click "SUBMIT" till when they fill all the questions.  But in this case we should indicate "where is not answered yet".   
2. Users can not click "次へ(next)" if they have not answered for each question
<img width="1437" alt="スクリーンショット 2021-10-12 16 06 29" src="https://user-images.githubusercontent.com/61481039/136908626-196e5d44-e9e2-44a7-b9f4-78605fb9815d.png">

**Comment by rgagne** [comment]
@sarikabhimre18 can you help Sho with this
@Show-M the Surgery form in Medigate Reference provides an example of this; you probably want to turn off the toolbar

**Comment by sarikabhimre18** [comment]
@Show-M Just need to change here and check in condition is value exists like below mention in image.
![Screenshot - 2021-12-08T102111 787](https://user-images.githubusercontent.com/29194144/145150205-bf0ca2fa-c7c8-4d09-bd63-e0fcc4a32b60.png)
M
