### ISSUE TITLE
Retrieve / pull  past-entry made when users open up tracker

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#213]
tracker [initial-registration] is an entry users make in their first signing-in process.
And possibly they will modify later when they get married etc...

As this data should be treated as a part of user profile, it does not make sense that users get empty  once they filled in and try to recall.
[step.mp4.zip](https://github.com/weaveio/woll-forum/files/7365631/step.mp4.zip)

**Comment by rgagne** [comment]
return to work
attributes vs wizard

**Comment by Show-M** [comment]
I think wizard is better as all the info collected in `tracker [initial-registration]` are work-related specific data.

this will solve #188

**Comment by rgagne** [comment]
Sent a chat message. This form is already wired to display for new users... 

Is the goal of this ticket to turn that into a wizard vs. a form?

**Comment by Show-M** [comment]
The goal is to retrieve the latest dispatch to the form every time when users open up profile edit.
So that, for users it looks like they just opened up saved profile info, edit and re-save.
<img width="368" alt="スクリーンショット 2021-12-15 12 24 43" src="https://user-images.githubusercontent.com/61481039/146117561-7294b807-ac2f-469a-963d-38bffc763d88.png">


Latest dispatch;
![IMG_0783](https://user-images.githubusercontent.com/61481039/146117489-b2b50f60-2f5b-494d-a714-3ce281628a48.jpeg)

**Comment by Show-M** [comment]
By Rob,
ok.. the process for that is a bit different.
dispatch => save metrics to user attributes => new dispatch, load the current user attributes
it doesn't retrieve the latest dispatch first.. it gets the data that the user entered from their attributes
i'll set that up.

**Comment by Show-M** [comment]
@rgagne  on-going?

**Comment by rgagne** [comment]
See https://docs.fluxweave.com/Scripting/Lua/07.Attributes/

The current approach is to:
1. Create a user schema matching the attributes in the tracker
2. Update that whenever a new copy of the tracker gets created (using the function above)
3. New updates to the tracker can load the data using fetchData on the tracker (an option)

Alternatively we could add a feature to the dispatch to retrieve the most recent copy of it ... is that better? Will it be helpful if this data is stored to the user profile?

**Comment by Show-M** [comment]
@rgagne 
It is better that retrieving the latest dispatch...something like the task board here but with no time range. 
Meaning, "latest dispatch from all time".
<img width="1265" alt="スクリーンショット 2022-02-08 11 53 00" src="https://user-images.githubusercontent.com/61481039/152973309-2c43a19f-64c5-4b1a-ae06-ef33bb0c743e.png">


this data does not have to be stored to user profile.

**Comment by Show-M** [comment]
By Rob
I am sure we already support what you need; please update the ticket clarify the requirements (the what) by specifying what attributes are captured, when they are captured and where they should be displayed.. we can then assign to Sarika. You can see https://docs.fluxweave.com/Tutorials/Attributes/ for details on how it can be connected.

**Comment by Show-M** [comment]
moving to #315
