### ISSUE TITLE
Weekly average dose rate per Morning/Noon/ Afternoon (週別の服用率 - test)

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#218]
Please create a following graph.
User "週別の服用率 - TEST" for this ticket.
<br>
<br>
Mockup:
<img width="799" alt="スクリーンショット 2021-10-25 12 25 17" src="https://user-images.githubusercontent.com/61481039/138630770-f199fcd8-a741-4622-ab79-784095fab2f4.png">

It will look similar to what we have now, But Monday/Tuesday.....instead of month
<img width="1178" alt="スクリーンショット 2021-10-25 12 35 21" src="https://user-images.githubusercontent.com/61481039/138631127-9ab7dece-cb19-4512-a873-323dd5017bb7.png">

**Comment by Show-M** [comment]
Hi Sarika, 
It looks getting closer but i do not think it is yet working properly.

`given user[sho.mitsuya.1005@gmail.com], given tracker[top2]`
The column saying "Day" was added by me manually.

displayName | when | Day | trackerName | data-444e447f-3860-4ef6-8adb-247f04fa33fe | data-cce40723-ed55-42bf-8c21-6c9a43b665a9 | data-expression | data-goal | data-medicine2 | data-morningActual | data-morningGoal | data-nightActual | data-nightGoal | data-noonActual | data-noonGoal | data-status
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Show-M | 2021-10-19 | Tuesday | Top 2 | 夜 | 昼,朝 | ◎ | 3 | [object Object],[object Object] | 1 | 1 | 1 | 1 | 1 | 1 | 3
Show-M | 2021-10-18 | Monday | Top 2 | 夜 | 朝 | ◯ | 3 | [object Object],[object Object] | 1 | 1 | 1 | 1 |   | 1 | 2
Show-M | 2021-10-15 | Friday | Top 2 |   |   | ✕ | 3 |   |   | 1 |   | 1 |   | 1 |  
Show-M | 2021-10-14 | Thursday | Top 2 | 夜 |   | ◯ | 3 | [object Object] |   | 1 | 1 | 1 |   | 1 | 1
Show-M | 2021-10-13 | Wednesday | Top 2 | 夜 | 朝,昼 | ◎ | 3 | [object Object],[object Object] | 1 | 1 | 1 | 1 | 1 | 1 | 3
Show-M | 2021-08-18 | Wednesday | Top 2 | 夜 | 昼 | ◯ | 3 | [object Object],[object Object] |   | 1 | 1 | 1 | 1 | 1 | 2
Show-M | 2021-09-21 | Tuesday | Top 2 | 夜 | 朝 | ◯ | 3 | [object Object],[object Object] | 1 | 1 | 1 | 1 |   | 1 | 2
Show-M | 2021-09-20 | Monday | Top 2 | 夜 | 昼,朝 | ◎ | 3 | [object Object],[object Object] | 1 | 1 | 1 | 1 | 1 | 1 | 3
<br>
<img width="1200" alt="スクリーンショット 2021-10-30 22 33 08" src="https://user-images.githubusercontent.com/61481039/139535005-38ba1d38-b9d7-4e5f-94bc-1379e6d423bf.png">
<br>
<br>
### I write down what i noticed.
According to the data, I have  1 entry on Thursday. 
data-nightGoal is 1.  data-nightActual is 1. This means on graph, Thursday should be 100% for Evening. 
But it is displayed as 9.09091...
<br>
Other percentages of Day are wrong too.
<br>
Monday/Tuesday....Sunday is not in order.

**Comment by Show-M** [comment]
@sarikabhimre18  
Kindly look up when you have time :)

**Comment by sarikabhimre18** [comment]
@Show-M Can you please take a look latest changes ?. As added a new data source[General-top2-year] which return only top2 tracker dispatches. Now calculation seem correct can you please verify once and let me know if have any changes ?.

**Comment by Show-M** [comment]
seems working great :)
