### ISSUE TITLE
Create the same data format as Asthma medicine list....

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#221]
Hi Sarika,

Can you kindly convert [Medicine data_selected.csv.zip](https://github.com/weaveio/woll-forum/files/7409393/Medicine.data_selected.csv.zip)
 into the same format/components as Asthma medicine?
(*Please pick data only with `Flag:1`* )
<img width="1437" alt="スクリーンショット 2021-11-03 11 47 09" src="https://user-images.githubusercontent.com/61481039/140003677-171c2d65-a617-415b-b485-fa95b60e1d72.png">

After your task, I will create a new medicine not on a new org :)

**Comment by Show-M** [comment]
@sarikabhimre18  
Please let me know when it is done :)

**Comment by sarikabhimre18** [comment]
@Show-M Is that a csv file ?

**Comment by sarikabhimre18** [comment]
@Show-M Please review the data below converted data and let me know if have any changes.
https://weave-io-files.s3.amazonaws.com/files/org/b15ea97f-754b-4c7f-8e8a-d8ea778385d0/EbKW2zhNnRWsleSXcAw8VIs6iginbn04067bc533887dac0fd86bfd2226cc60/MData.json
