### ISSUE TITLE
Creating proper graph in PDF ideally

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#222]
Page Dr want to export:  https://web.weave.io/8e63fc1d-5dcf-42cc-8eef-84af6464a9a2/page-search/patient-graph/p3
Goal: Dr can see the graph page on electoric Medical record, which has no internet connection but USB connector.

"Proper" means the PDF that can display ALL the graph on the page properly without over-wrapping.

Currently, when user try to export the page, it does not  get exported properly.
[Fluxweave-graph.pdf.zip](https://github.com/weaveio/woll-forum/files/7520870/Fluxweave-graph.pdf.zip)

Current step;
1. right click
2. click "print"
3. choose "save as PDF"
<img width="1417" alt="スクリーンショット 2021-11-11 22 54 57" src="https://user-images.githubusercontent.com/61481039/141310643-b920b2ed-5310-4e6c-be7c-297383cad015.png">

**Comment by Show-M** [comment]
Dr said "PDF". But i can check if other formats are ok if needed. 
the requirement is that they can see all the graph in a file without the internet.

Any details you want to know or suggest? @rgagne

**Comment by rgagne** [comment]
we can format the page to make it appropriate for printing; will work on that

**Comment by rgagne** [comment]
@sarikabhimre18 can you apply the setting for this to make it work?

**Comment by sarikabhimre18** [comment]
@Show-M Setup a print button in header like you can test with latest build and let me know if have any changes.
![Screenshot (39)](https://user-images.githubusercontent.com/29194144/148883127-7a283bca-b12b-4366-a313-03626239c95d.png)

**Comment by Show-M** [comment]
i will close this but a bug detected and reported to #269
