### ISSUE TITLE
November New Medicine Data

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#224]
When you have time, can you convert them for medicine note?
It is not urgent.

I shared the data with sarika@fluxweave.com
https://drive.google.com/file/d/19Fs79O4XPrWFCDLpO7N5VoA9Ig5kzOnK/view?usp=sharing

Steps: #120

**Comment by sarikabhimre18** [comment]
@Show-M Here is the converted data 
https://weave-io-files.s3.amazonaws.com/files/org/b15ea97f-754b-4c7f-8e8a-d8ea778385d0/TpzFt3v5Qnh3H0h8F2ElYw48enQowW6077a8672a23c92a5a2a8c614196f904/xml19_dosageChange.json

Please review and let me know if have any changes.
Thank you !

**Comment by Show-M** [comment]
It is good to go @sarikabhimre18 

Please upload it :) 

btw do you upload these json data by copy & paste to fluxweave? or upload the file to somewhere?

**Comment by sarikabhimre18** [comment]
@Show-M 
Just copy paste to fluxweave.

**Comment by Show-M** [comment]
Got it and i did it :)
