### ISSUE TITLE
Why attachment bar on the bottom is still visible even if "attachment is hide" on Admin setting?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#225]
<img width="1435" alt="スクリーンショット 2021-11-20 11 43 27" src="https://user-images.githubusercontent.com/61481039/142712040-21490df3-703d-4074-b246-91ad069228de.png">

<img width="336" alt="スクリーンショット 2021-11-20 11 51 31" src="https://user-images.githubusercontent.com/61481039/142712082-5b6a4876-997f-47b4-ae83-9c1273fe0f61.png">

**Comment by Show-M** [comment]
Is this a bug or some configuration set wrong? @rgagne

**Comment by Show-M** [comment]
never mind...its gone. sorry.

**Comment by Show-M** [comment]
actually it is still there...

**Comment by rgagne** [comment]
It's the one highlighted; attachment is for the right side menu
![image](https://user-images.githubusercontent.com/428897/145026646-782ce1f3-8c28-4166-9563-252212c54d35.png)

Seems to be working now; not seeing the menu

**Comment by rgagne** [comment]
OK... 1st time = working, 2nd time and more = not working.. that's a bug.. but not an obvious problem from the initial description.

Bug filed for this: https://github.com/weaveio/platform/issues/2576
