### ISSUE TITLE
Add a checkbox specifically for Return-to-work org on Invite code screen.

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#226]
Currently we have only 1 checkbox for every org on Chant to get consensus. 
Goal: Let return-to-work research-study to get accepted by ethical committee for using Chant app
Requirement: Specifically for Return-to-org,  we add 1 more checkbox with a specific sentence for the org.
Note: The new check box must be exactly on the image 2.

![IMG_0740](https://user-images.githubusercontent.com/61481039/143190538-49e63373-2dc6-4f38-b3c9-9b1d826c4c2f.png)

![IMG_0739](https://user-images.githubusercontent.com/61481039/143190441-dab54e84-a77c-4772-b8ed-ca2deccb8d66.png)
)

**Comment by rgagne** [comment]
Ready for admin; requires latest build (already in testflight, will publish)

**Comment by Show-M** [comment]
Great :)  @rgagne 

A question: What am i supposed to write? 
<img width="1277" alt="スクリーンショット 2021-12-07 22 20 57" src="https://user-images.githubusercontent.com/61481039/145036662-dc3af796-a152-4d62-887a-aafd7ddefb57.png">
