### ISSUE TITLE
New graph: Create Seasonal dose rate graph last 1 year

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#227]
<img width="1439" alt="スクリーンショット 2021-11-30 18 51 39" src="https://user-images.githubusercontent.com/61481039/144026537-8edf41da-1fc4-4056-b2b1-ba2ff68b3b8c.png">

Please create Seasonal dose rate graph with data collected from last 1 year. 
You can create new one on the bottom
There will be 4 seasons:

Winter: 12-2
Spring: 3-5
Summer: 6-8
Autumn: 9-11

I believe that we just have to modify "timeseries"...

`
  "tile": "chart",
  "display": {
    "span": "12"
  },
  "chart": {
    "title": "Values by month",
    "timeSeries": "YYYY-MM; YYYY-MM-DD; P1M",
    "c3": {
      "data.type": "bar",
      "size.height": 250,
      "axis.y.show": true,
      "axis.x.tick.format": "%b",
      "legend.show": true,
      "grid.y.lines[0].value": "50",
      "axis.y.max": 100
    }
  },
  "connect": [
    {
      "title": "朝の服用率",
      "trackerHandle": "top2",
      "source": "general-year",
      "pick": "(ifNaN(values.morningActual/values.morningGoal, 0))*100",
      "apply": "mean(ls)",
      "format": "0,0",
      "tableData": {
        "id": 0
      }
    },
    {
      "title": "昼の服用率",
      "trackerHandle": "top2",
      "source": "general-year",
      "pick": "(ifNaN(values.noonActual/values.noonGoal, 0))*100",
      "apply": "mean(ls)",
      "format": "0,0",
      "tableData": {
        "id": 1
      }
    },
    {
      "title": "夜の服用率",
      "trackerHandle": "top2",
      "source": "general-year",
      "pick": "(ifNaN(values.nightActual/values.nightGoal, 0))*100",
      "apply": "mean(ls)",
      "format": "0,0",
      "tableData": {
        "id": 2
      }
    }
  ],
  "title": "月別の服用率 -test"
}
`

**Comment by sarikabhimre18** [comment]
@Show-M Here is the current scenario. Please review and let me know if have any changes. 
![Screenshot - 2021-12-01T164221 993](https://user-images.githubusercontent.com/29194144/144224930-c1513996-8aab-40ab-a03d-05a5ec52ae7a.png)

**Comment by rgagne** [comment]
Just to confirm @sarikabhimre18 is this following the seasonal periods that show listed above or is it quarters? I ask because I am not sure we support what Sho is asking for.

Winter: 12-2, e.g. Dec through Feb
Spring: 3-5, Mar through May
Summer: 6-8, June through Aug
Autumn: 9-11, Sep through Nov

**Comment by sarikabhimre18** [comment]
@rgagne May be for grouping data is that helpful https://stackoverflow.com/questions/5670678/javascript-coding-input-a-specific-date-output-the-season/54501026.

**Comment by sarikabhimre18** [comment]
@rgagne Just for information every country have different season month ?.

**Comment by Show-M** [comment]
@rgagne  
Can you answer to Sarika's question? So that, we can proceed.

**Comment by rgagne** [comment]
@sarikabhimre18 I think you mean `Math.floor((d.getMonth() / 12 * 4)) % 4`  and not the lunatic answer above it .. but that's not the hard part. The hard part is that we pass the string to moment for parsing.

@Show-M not a simple fix; will come back to it

**Comment by sarikabhimre18** [comment]
@rgagne Okay will need to do some investigation on it how can if pass string to moment.

**Comment by Show-M** [comment]
thank you Rob, and Sarika :)

@rgagne 
So, you defined seasonal as  below. Are they configurable ? 
Winter: 12-2
Spring: 3-5
Summer: 6-8
Autumn: 9-11
