### ISSUE TITLE
Provide answers to 2 questions from Ethical Committee  for "Condition for users" on Invite code input page on mobie.

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#230]
<img width="1417" alt="スクリーンショット 2021-12-07 18 17 54" src="https://user-images.githubusercontent.com/61481039/145004600-41c3b79f-64ce-4d89-9250-b2673aca44ad.png">

There are 2  questions aka RQ...

1. All the texts within the box are plain and difficult to read.  Can we apply  "font size/bold/Italic/spacing" ? 
2. Can we add images in ? (Here, ethical committee meant images of fitbit)

審査委員５の１）の説明文書の
> １）全体的に、項目も同じフォントで読みにくく感じます。
> 　　項目で、行間を空けるなどすると読みやすくなると思います。

ですがここは調整可能でしょうか？

追加で申し訳ありませんが、
審査委員５の3の説明文書にfitbit写真が入れられるかも合わせてお願いします。

**Comment by rgagne** [comment]
It supports markdown so the answer to both is yes.. however take care when adding images so that they are not big (either file size or display size). I would encourage not using images.. but I can help if needed.

**Comment by Show-M** [comment]
Thx. 
Well, I assume at least 1 image will be necessary as "ethical committee" wont listen....but will talk with the Dr if we can avoid that.

**Comment by Show-M** [comment]
Dr will try without  image against the committee
