### ISSUE TITLE
Create time series scatter graph

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#231]
Original title: "Create Time clock based point-graph"

Image:
<img width="848" alt="スクリーンショット 2021-12-07 19 52 55" src="https://user-images.githubusercontent.com/61481039/145016343-f50a995c-075c-413f-95c8-3a58aa5f85b4.png">

Goal: Doctors can see how often patients have attacks, plus time tendency.
Tracker: attack
Example data source: given tracker[attack], given user[sho.mitsuya.1005@gmail.com]
Data range: it depends how often users have attacks...so it should be 1month/6month for now
X-axis is DATE ( dispatch date)
Y-axis is TIME (values.time)

# Tasks

- [x] Implement scatter chart per https://github.com/weaveio/platform/issues/2546
- [x] Configure this particular scatter chart

**Comment by Show-M** [comment]
24が下。0が上 Y軸

**Comment by Show-M** [comment]
@sarikabhimre18 
Org: https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c/stream/~/p0
Can you create this?

**Comment by sarikabhimre18** [comment]
@Show-M Can you please clarify bit more ?. There doesn't having a tracker seizure. what dose tracker seizure contain ?. Which data you want to show in chart ?.

**Comment by Show-M** [comment]
@sarikabhimre18 
updated..sorry my mistake :v

**Comment by sarikabhimre18** [comment]
@Show-M Fixed this in latest changes can you please review and let me know if have any changes.
![secanrio1](https://user-images.githubusercontent.com/29194144/146313714-e39f0f8c-df8d-4a9b-8fa3-29850e39883f.png)

**Comment by Show-M** [comment]
@sarikabhimre18 
Few comments:

1.  Y-axis is TIME (values.time). that means max  value on Y-axis should be 24 as 1 days has 24h.
<img width="589" alt="スクリーンショット 2021-12-17 11 56 42" src="https://user-images.githubusercontent.com/61481039/146481768-29259de7-eec5-4bb0-86e6-7155a0485fba.png">


2. When there are multiple entries in 1 day, it should be reflected..
For example, there are 2 entries for 5th of Dec. Then there should be 2 dots.
<img width="777" alt="スクリーンショット 2021-12-17 11 56 54" src="https://user-images.githubusercontent.com/61481039/146481862-c0989dc5-48ac-4213-a65d-f581aadf4e96.png">

**Comment by rgagne** [comment]
@Show-M if the data value is same day same time then there will be two dots but they will be one on top of the other... not really much we can do
@sarikabhimre18 why does the data go > 30? is this the time metric that lets the user select time past midnight?

**Comment by rgagne** [comment]
@Show-M discussed with @sarikabhimre18 and the problem is that we group by day (with a transform function to turn a series into a single data point)... because that's the way most charts work.

However with the scatter you want multiple values in a single date.. we need to create a new chart type for it.

**Comment by sarikabhimre18** [comment]
related https://github.com/weaveio/platform/issues/2546

**Comment by Show-M** [comment]
I understand, guys. 
and thank you for working on this, @sarikabhimre18 👍

**Comment by sarikabhimre18** [comment]
@Show-M Please review the changes in latest build. Current scenario in below image. 
![Screenshot (8)](https://user-images.githubusercontent.com/29194144/147344609-c6e4bbb6-f6ae-439b-bc2f-8efd62ab7d26.png)

Thank you !

**Comment by rgagne** [comment]
@Show-M can you confirm this meets requirements?

**Comment by Show-M** [comment]
@sarikabhimre18 

What i see now is below.  I believe you created on ATTACK GRAPH - TEST 1. 
Then it seems that it is working as the Dr expect.
<img width="1362" alt="スクリーンショット 2022-01-05 11 41 21" src="https://user-images.githubusercontent.com/61481039/148204483-56de251a-45d7-4377-920d-4188a956e8d0.png">


Thank you!
