### ISSUE TITLE
Medicine data- Converting/Displaying original data in a non proper way

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#233]
## Upper/Lower case issue -  "MG" to "mg"

The original data is all lower case. - `This is correct.`
<img width="1368" alt="スクリーンショット 2021-12-13 1 32 35" src="https://user-images.githubusercontent.com/61481039/145720858-0eb155f5-3275-4701-b7d1-72846af4bcec.png">

But when we see on the medicine note, they are all upper case - `this is wrong`
<img width="776" alt="スクリーンショット 2021-12-13 1 42 23" src="https://user-images.githubusercontent.com/61481039/145721196-1aabb079-ac80-4d67-bbf7-afc0f95b41ec.png">

After the discussion with Dr, it is very important to display as mg, Not MG. as it stands for "milligram"
Can you look into why this upper/lower case change is occurring and fix it?

## Converting issue - "μg" to "MG"

The original data is all "μg". - `This is correct.`
<img width="1353" alt="スクリーンショット 2021-12-13 1 45 44" src="https://user-images.githubusercontent.com/61481039/145721298-2e1834af-035f-467c-8425-d0e8d9c2d51e.png">

But when we see on the medicine note, they are all "MG" - `this is wrong`
<img width="834" alt="スクリーンショット 2021-12-13 1 46 12" src="https://user-images.githubusercontent.com/61481039/145721314-97489656-b5ef-4ffa-96a1-ac357b8bd409.png">

**Comment by sarikabhimre18** [comment]
@Show-M Fixed this in latest changes current scenario look like below.
![Screenshot - 2021-12-13T103717 418](https://user-images.githubusercontent.com/29194144/145755685-32c25a21-2923-4e1b-9ec9-d18a006a
![Screenshot - 2021-12-13T103733 858](https://user-images.githubusercontent.com/29194144/145755693-b6f6a560-235b-4036-9d8d-e3d1593a28d2.png)
b4d3.png)

**Comment by Show-M** [comment]
@rgagne 
Just to check, i dont see  this change applied yet. is it already implemented?
