### ISSUE TITLE
Task board: Display a message after making entries with score and phrase(pre-conditioned)

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#239]
<img width="1413" alt="スクリーンショット 2021-12-09 16 35 11" src="https://user-images.githubusercontent.com/61481039/145353609-1b7d02f7-4f4f-4d6d-8e79-76c236827642.png">

<img width="435" alt="スクリーンショット 2021-12-09 16 35 59" src="https://user-images.githubusercontent.com/61481039/145353678-4d17af48-a8cb-4b8c-9318-a4f6515af37f.png">

Phrase should be: 
Your point is  `values.CACTQ411total OR values.CACTtotal `.  POOR/So-So/Good/Great!
<img width="1114" alt="スクリーンショット 2021-12-09 16 41 22" src="https://user-images.githubusercontent.com/61481039/145354518-ac6811c9-e0fc-4789-b387-9fa1f8899d42.png">

Note:
Maximum points differ by cactage,    "4〜11歳" or  "12歳以上"
<img width="1105" alt="スクリーンショット 2021-12-09 16 41 14" src="https://user-images.githubusercontent.com/61481039/145354446-d1c8ec94-607d-460a-9288-1bbc5d654824.png">

POOR/So-So/Good/Great display score condition:
values.cactage is '4〜11歳'     Point Max 27
POOR: 0-7
so-so: 7-14
good: 14-22
great: 22-27

values.cactage is '12歳以上'      Point Max 25
POOR: 0-10
so-so: 10-15
good: 15:20
great: 20-25

**Comment by Show-M** [comment]
@rgagne  is this a new function, i guess?

**Comment by rgagne** [comment]
that's not in the tracker it's in the layout - home - and already supported

Currently the display is configured as 
```
"display": [
    {
      "condition": "props.count > 0",
      "title": "ぜん息日記",
      "subtitle": "既に入力済みです!",
      "icon": "fad fa-mountain",
      "status": "complete",
      "animation": {
        "root": {
          "entry": "flipInX"
        }
      }
    },
    {
      "condition": "true",
      "title": "ぜん息日記",
      "subtitle": "入力して下さい",
      "icon": "fad fa-mountain",
      "status": "new"
    }
  ]
```

connect is configured as 
```
{
    "title": "top",
    "source": "top",
    "pick": "1",
    "apply": "sum(ls)",
    "trackerHandle": "top"
  }
```

If you make changes to these you can display different messages for different conditions

**Comment by Show-M** [comment]
@rgagne 
Questions:
1.  There is a condition,  `"condition": "props.count > 0"`. I will need 2 conditions, which will be something like `"condition": "props.count > 0 and values.CACTQ411total>=25"`.  What are correct way to display ?
2. In order to display a text with score such as `Your point is {values.CACTQ411total}. POOR`, what are required?

**Comment by Show-M** [comment]
@rgagne   let me know this.

**Comment by rgagne** [comment]
@sarikabhimre18 - can you configure this the way Sho is requesting? there should be enough functionality to make it work properly without any coding

As always - document as you go!

**Comment by sarikabhimre18** [comment]
@rgagne 
Questions:-
-) For total currently we didn't get ``` values.CACTQ411total``` in dispatch there are two way to support it  either we support attribute sum in condition like (values.val1 + values.val2 ) >=  5 or process compute field in markup task component. Which on we are using ?. But still having issue in process in markup task component. We are not able the data when making entires.

**Comment by sarikabhimre18** [comment]
@rgagne Needed to process compute rule in tasks so fixed this issue here https://github.com/weaveio/client.root/pull/355. Configure a rule as per above description.
![Screenshot - 2022-02-08T124728 600](https://user-images.githubusercontent.com/29194144/152937520-5a782b28-cb37-4085-b6f2-6a69ee72550f.png)

@Show-M Please review once it merge with master one by @rgagne .
Thank you !

**Comment by Show-M** [comment]
For myself

Message: 
values.cactage is '4〜11歳' . Point Max 27
POOR: 0-7   -  {values.CACTQ411total}点です。まだまだです
so-so: 7-14 -  {values.CACTQ411total}点です。まあまあです。
good: 14-22 -  {values.CACTQ411total}点です。なかなか良いです!
great: 22-27 -  {values.CACTQ411total}点です。素晴らしいです!!

values.cactage is '12歳以上' . Point Max 25
POOR: 0-10 -  {values.CACTtotal}点です。まだまだです。
so-so: 10-15 -  {values.CACTtotal}点です。まあまあです。
good: 15:20 -  {values.CACTtotal}点です。なかなか良いです!
great: 20-25 -  {values.CACTtotal}点です。素晴らしいです!!
