### ISSUE TITLE
Allow Dashboard to move/forward 1 day(+/- 3 days max)

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#240]
Currently swiping either right or left does not change the date but stays as TODAY.
<img width="1424" alt="スクリーンショット 2021-12-09 17 15 36" src="https://user-images.githubusercontent.com/61481039/145359195-dff70701-c6ec-48d5-9f1d-68177e4a62b1.png">

How it behaves now:
[RPReplay_Final1639037791.mp4.zip](https://github.com/weaveio/woll-forum/files/7683341/RPReplay_Final1639037791.mp4.zip)

**Comment by rgagne** [comment]
already fixed
