### ISSUE TITLE
auto-calculation for Peak-Flow standard based on profile info 

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#246]
## Data to collect

In order to calculate the standard value of Peak-flow, we need following data input by users
- height
- age
- gender

### Note
We currently do not have height info. It is possible to add new tracker and ask users to fill in during profile creation. 
But it might be a bit weird to have a tracker just for height. 
Can we add height as an optional item to be filled on profile?
<img width="399" alt="スクリーンショット 2021-12-12 22 23 55" src="https://user-images.githubusercontent.com/61481039/145714103-d336ef0e-10df-4e75-b22b-3b9efa7431bf.png">

### Formula
●Male: (L /分)＝77.0 ＋ 64.53 ×height(m)^3 ＋ 0.4795 × age^2
●Female:  (L /分) ＝ −209.0 ＋ 310.4 × height(m)＋ 6.463 × age

## Where to display
Within Top2 tracker
<img width="441" alt="スクリーンショット 2021-12-12 22 24 07" src="https://user-images.githubusercontent.com/61481039/145714106-f0b43de4-b6b5-402d-b170-66f1602538aa.png">

**Comment by rgagne** [comment]
@Show-M - make a tracker with what you want; configure it as the intake / edit wizard

Example:
![image](https://user-images.githubusercontent.com/428897/152752519-df597c98-5f3a-4603-9469-91c00c8c7958.png)

**Comment by Show-M** [comment]
@rgagne I found a bit odd to have a tracker just for height...if we can configure easily user profile, that would be great though... For now i will do per your instruction.

**Comment by Show-M** [comment]
### Components:
height:   tracker:height, matrix:height
age:  profile.age

### Formula:
●Male: (L /分)＝77.0 ＋ 64.53 ×height(m)^3 ＋ 0.4795 × age^2
●Female: (L /分) ＝ −209.0 ＋ 310.4 × height(m)＋ 6.463 × age

### Where to display:
https://user-images.githubusercontent.com/61481039/145714106-f0b43de4-b6b5-402d-b170-66f1602538aa.png

**Comment by Show-M** [comment]
@rgagne  
To display, i thought maybe i can use "compute"...but it is supported only on display mode, not entry mode?

**Comment by Show-M** [comment]
@rgagne  ?

**Comment by Show-M** [comment]
moved.
