### ISSUE TITLE
Create a graph: How much mg(milligram), what medicine & how much duration 

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#248]
Sample user: Show-M
`Tracker: med` 
Y axis:  mg(milligram), `metric: amount1/2/3`
X axis:  duration,   `dispatch creation data`
Data range: 6 months / 1 year

Important: 
We track each Line graph by its name, the **actual data** of `metric: name1/2/3`. 
It is possible that users stop using a certain medicine, and restart to use at some point.
What i meant is below;
```
  "$data": {
    "source": [
      {
        "display": "アレビアチン",
        "value": "アレビアチン",
        "tableData": {
          "id": 0
        }
      },
      {
        "display": "イーケプラ",
        "value": "イーケプラ",
        "tableData": {
          "id": 1
        }
      },
      {
        "display": "エクセグラン",
        "value": "エクセグラン",
        "tableData": {
          "id": 2
        }
      },
      {
        "display": "ガバペン",
        "value": "ガバペン",
        "tableData": {
          "id": 3
        }
      },
      {
        "display": "デパケン(セレニカ)",
        "value": "デパケン(セレニカ)",
        "tableData": {
          "id": 4
        }
      },
      {
        "display": "トピナ",
        "value": "トピナ",
        "tableData": {
          "id": 5
        }
      },
      {
        "display": "ビムパット",
        "value": "ビムパット",
        "tableData": {
          "id": 6
        }
      },
      {
        "display": "フィコンパ",
        "value": "フィコンパ",
        "tableData": {
          "id": 7
        }
      },
      {
        "display": "フェノバール",
        "value": "フェノバール",
        "tableData": {
          "id": 8
        }
      },
      {
        "display": "マイスタン",
        "value": "マイスタン",
        "tableData": {
          "id": 9
        }
      },
      {
        "display": "ラミクタール",
        "value": "ラミクタール",
        "tableData": {
          "id": 10
        }
      },
      {
        "display": "ランドセン",
        "value": "ランドセン",
        "tableData": {
          "id": 11
        }
      },
      {
        "display": "リボトリール",
        "value": "リボトリール",
        "tableData": {
          "id": 12
```

Example graph:
As you can see, Medicine 2 has about 2 months blank
<img width="794" alt="スクリーンショット 2021-12-14 14 00 34" src="https://user-images.githubusercontent.com/61481039/145936082-e1416f95-9f3d-4d2b-bdbe-c2c33121b2ed.png">

**Comment by sarikabhimre18** [comment]
@Show-M Is this org https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c/admin/dataService ?

**Comment by rgagne** [comment]
this is the difference between sparseChart and chart... chart requires data for every point but sparse chart will connect even if there is no data point

@Show-M can you let Sarika know which org and which chart?

**Comment by Show-M** [comment]
@sarikabhimre18 

The org is https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c/admin/dataService .
Location to create a graph:
<img width="591" alt="スクリーンショット 2021-12-15 16 56 09" src="https://user-images.githubusercontent.com/61481039/146146136-45acf4d2-c9e7-4ee8-9372-ac5a3942586f.png">

**Comment by Show-M** [comment]
階段グラフ。
5mlとか1000mlとかがあり、単位統一がむずかしい。

**Comment by Show-M** [comment]
Check with Dr:
Can we use "dose" ? caz we need a common scale.

**Comment by rgagne** [comment]
@Show-M assigning to you until the requirements are clear; if you can update the initial body with the final requirements that will be helpful

**Comment by Show-M** [comment]
https://c3js.org/samples/chart_step.html

![Uploading スクリーンショット 2021-12-15 22.34.02.png…]()

**Comment by Show-M** [comment]
email sent. waiting for the response

**Comment by Show-M** [comment]
@rgagne 

Issue:
There will be 3 different measurement for dosage of medicines. And Dr wants to display all in 1 graph
- Medicine type A: 0 - 5000 ml
- Medicine type B: 0 - 500ml
- Medicine type C: 5 - 20ml OR 0.5 - 2ml

Plus, 
- Name of medicine
- Use-duration of each medicine 

Then how about graph like below? is that even possible to create? 
<img width="787" alt="スクリーンショット 2021-12-19 18 41 21" src="https://user-images.githubusercontent.com/61481039/146670394-d29fdf83-76cd-404a-86fd-e86056ecc25b.png">

**Comment by Show-M** [comment]
@rgagne  need your response.

**Comment by rgagne** [comment]
@Show-M - from the last post this seems to be just a regular chart grouped by metric
@sarikabhimre18 - can you work with show to set this up?

**Comment by sarikabhimre18** [comment]
@rgagne As reviewing configure the chart. 
Questions:-
-) Is that possible to we group data by multiple pick values without any operation ?

**Comment by rgagne** [comment]
@sarikabhimre18 - yes, = regular chart grouped by metric
also reminder that if you don't put it in "need feedback" very likely I won't see the comment
