### ISSUE TITLE
Consensus screen for Fitbit-use; After users join in the org

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#253]
## Goal
Users can agree/disagree to Fitbit-use consensus whenever they want

## Requirement
- Users can agree to  Fitbit-use consensus in 2 touch-points mentioned below
- Users can disagree to Fitbit-use consensus even after they agreed once
- In order to let users disagree, Dr would like to add "open up email and make users to write a message about quitting the research" step

### Agree screen
It should be reachable on 2 touch-points.

1. Right after the user join the org aka after tapping "COFIRM" screen for the first time.
2. Somewhere reachable by users from side menu in regular basis

2 is required because 
- Using Return-to-work app and participating in fitbit-use research are different thing
- Therefore there are cases where users disagreed in the first place but will  decide to  participate in the research after starting to use the app

### Disagree screen
It should be somewhere reachable by users from side menu in regular basis.
This screen will be used if users decide to quit fitbit-use research. And Dr needs to keep the record of each user's disagreement.

### Consensus contents check-up screen
This can be done by wiki.

## My thought

1. Create a screen like this below and make disagree button disable or invisible on "Agree screen scenario 1).
![研究参加同意を取り消す drawio](https://user-images.githubusercontent.com/61481039/149318236-9ee2eeb9-9d3e-4bb7-814e-4c279b572c50.png)

2. Create "agree screen" and Add "disagree" button in "Consensus contents check-up screen".

**Comment by Show-M** [comment]
@rgagne  This is a priority. Without this function, Dr can not start his project.

**Comment by rgagne** [comment]
We need to create a way for users to connect their Fitbit devices which involves the following steps

1. User clicks "Add integration" within our app
2. User selects Fitbit from the options (we can probably configure this so it just displays Fitbit)
3. User is taken to Fitbit website to login (via a Safari or in app browser)
4. User authenticates with Fitbit and then agrees that Fluxweave can access their data
5. User is taken back to the app

Later the user can 

1. Within the Fitbit app or Fitbit website disable the integration
2. Within our app disable the integration

How does the above requirements fit with this? It seems like this process would be in place of what's described above.

**Comment by Show-M** [comment]
Preferably  it is better if we can disable integration within our app. 

In the step above,  "add integration" button can be placed in:
1. next screen after " i agree to fitbit-use"
2. somewhere visible  in the app

In the step above, "disable integration" should appear only after " i disagree/quit fitbit-use".

Theoretically, it makes the most sense that "add integration" button appear only in scenario 1.  but it seems that Dr was told to add "agree screen" by ethical committee to display after the "chant app agreement" screen during user's first time log-in. 

I can double check if `"add integration" button appear only in scenario 1` is ok for Dr if you also think this makes the most sense. What do you say? @rgagne

**Comment by rgagne** [comment]
The main point is that the integration with Fitbit is separate from the agreement and they cannot be combined into the same flow. Integrating Fitbit requires calling into the Fitbit API and actually taking the user out of the app and to the Fitbit website to approve the integration. 

We can provide the ability to disable the integration within the app. We can also only show integration option once they've accepted the other agreement.

**Comment by Show-M** [comment]
> The main point is that the integration with Fitbit is separate from the agreement and they cannot be combined into the same flow. Integrating Fitbit requires calling into the Fitbit API and actually taking the user out of the app and to the Fitbit website to approve the integration.

Right. But displaying to users as if they are in the same flow should be ok?

**Comment by Show-M** [comment]
@rgagne  Is this sufficient?
![PXL_20220126_103531206](https://user-images.githubusercontent.com/61481039/151148280-67c303ca-befc-4a32-a4e5-b7305b1d391f.jpg)

**Comment by Show-M** [comment]
@rgagne  we have to build this...Dr is pretty much waiting for this to be live. 
So that, they can get a final permission from ethical committee..

**Comment by rgagne** [comment]
@Show-M I added a layout which could be hard coded to do what's needed as well while the actual thing gets built out

**Comment by Show-M** [comment]
@rgagne 
The layout you added looks a bit far from how we are planning to make it look like in the end?

And we need to submit our final product to ethical committee for approval...I am not sure how the  #2600 will look like in the end though.   Improvement is definitely necessary..

**Comment by Show-M** [comment]
Fitbit同意書のテキストはある？

**Comment by Show-M** [comment]
テキスト待ち。
