### ISSUE TITLE
Can you change/delete these buttons  as they are not functioning ?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#254]
these buttons are there for Eating disorder to move forward/backward days. But they are not necessary and therefore not functioning on this graph page. Please remove(or use different target?)
<img width="1399" alt="スクリーンショット 2021-12-17 12 00 59" src="https://user-images.githubusercontent.com/61481039/146482246-3ac54ead-b29b-4c8f-8766-2874113124e0.png">

**Comment by rgagne** [comment]
it needs to be the same target because it carries the user in
