### ISSUE TITLE
clock-single; let the user specify the granularity of the picker

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#256]
## Goal

Provide a way to change the granularity of the time picker

## Requirements

Add `$capture.minutesStep` option that is passed to the component for "clock-single". This should allow the user to specify 1, 5, 10, etc. and the picker would only allow those increments.

Timer picker component: https://material-ui-pickers.dev/api/TimePicker; see minutesStep attribute that it offers, should still default to 1.

Current Tracker config
```
  "time": {
    "type": "string",
    "$capture": {
      "as": "clock-single",
      "confirm": false,
      // support gets added here
    },
    "title": "受診時刻"
  }
```

## Original request

Currently, the clock minimum unit is 1min. Can we change it to 15min?

Configuration
https://user-images.githubusercontent.com/61481039/146638150-618e989f-9489-4b5c-93ec-6f60d0674200.png

**Comment by Show-M** [comment]
@rgagne  is this a new function RQ or ?

**Comment by rgagne** [comment]
it's a feature request; i've updated the ticket with the requirements

**Comment by sarikabhimre18** [comment]
@rgagne Supported provided above things. But one questions is that also increment value when user changes the date ? 
![Screenshot (70)](https://user-images.githubusercontent.com/29194144/150096273-99ae0f62-6f75-4411-b8a4-5dbd37abc9c5.png)
