### ISSUE TITLE
Completing 1 task change status of 2 tasks  [wrong behavior]

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#257]
<img width="1140" alt="スクリーンショット 2021-12-18 23 12 26" src="https://user-images.githubusercontent.com/61481039/146644213-df57a502-2154-48c6-bfc9-8c83778c55f4.png">

<img width="439" alt="スクリーンショット 2021-12-18 23 15 01" src="https://user-images.githubusercontent.com/61481039/146644113-960446f3-259e-4ed0-a909-2f23b422aa14.png">

org: https://web.weave.io/634f007d-8fdf-45e4-b3a0-6d3a61cf04f5/stream/~/p0
I think it is something about the layout i set up...But i could not find the cause.
On task board,
Competing ② makes ① & ② makes COMPLETE. Then  When i open ①, it displays the dispatch of ② - Wrong behavior
Step:
[step.mp4.zip](https://github.com/weaveio/woll-forum/files/7739377/step.mp4.zip)

Completing ① does not trigger any wrong behavior..

**Comment by rgagne** [comment]
Filter is the correct place to put the tracker handle; it was there for 2 and 3 but not 1. Additionally you can have them all on a single tile.
