### ISSUE TITLE
Automatic selection of values based on user profile

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#261]
<img width="1399" alt="スクリーンショット 2021-12-19 22 16 10" src="https://user-images.githubusercontent.com/61481039/146676197-e2ad5743-4e64-4507-9d9e-fb35b4c00996.png">
<img width="1061" alt="スクリーンショット 2021-12-19 22 16 40" src="https://user-images.githubusercontent.com/61481039/146676204-5d04642e-99f9-44af-be4a-24569578e2dd.png">

Tracker: cact

Conditions for automatic selection based on user age.
1. If the user is younger than 12,  "4〜11歳" will be selected
2. If the user is 12 or above,  "12歳以上" will be selected

Goal: 
1. `matrix: cactage` choose and fix its value automatically based on their ages registered on user profile when users open the tracker.   (See conditions above)
2. Proper matrix will be displayed to users based on preset conditions(values.cactage is '4〜11歳' & values.cactage is '12歳以上')

**Comment by rgagne** [comment]
@Show-M we have age in the profile so you can simply change the rule to `profile.age < 12` 

Are users setting their age properly?

**Comment by Show-M** [comment]
We will use `profile.age < 12` `and profile.age >= 12` instead for appropriate matrix. 

Before that we need to ask Dr to make patients add their date of birth properly.
<img width="1060" alt="スクリーンショット 2022-01-18 11 29 27" src="https://user-images.githubusercontent.com/61481039/149920232-ff12d08f-7fa2-4d46-b8b1-977e99f23c55.png">

**Comment by rgagne** [comment]
we may have made it optional because of some earlier requests; we can change that

**Comment by Show-M** [comment]
自動振り分け　＋　手動選択式　を同時表示させる。

**Comment by Show-M** [comment]
@rgagne 
is it possible to have manual selection(radio in tracker) & automatic selection(by profile age) on the same tracker?
- If the profile.age is empty, system displays manual selection
- if the profile.age is filled, system does automatic selection (manual selection will not be displayed)

**Comment by rgagne** [comment]
yes using `exists` and `or` it should be possible 

show the radio with `profile.age exists` or `profile.age empty` and then the others with `profile.age < 12 or values.whatever is 'something'`

**Comment by Show-M** [comment]
created as  (C-)ACT-test. Ready to copy & paste to the actual tracker anytime. 
Only visible to Dr for now.
