### ISSUE TITLE
Question about dispatch for "attack tracker"

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#266]
https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c/admin/trackers

When i open dispatched, "発生時刻" is missing. I believe I need to change "how to display" from Data to something else.
What can we change here to without affecting the graph,   "ATTACK GRAPH - TEST 1"? 
<img width="971" alt="スクリーンショット 2022-01-05 11 42 40" src="https://user-images.githubusercontent.com/61481039/148205029-68709993-035e-4f2a-aff2-7033d1aeb304.png">
<img width="1135" alt="スクリーンショット 2022-01-05 11 42 54" src="https://user-images.githubusercontent.com/61481039/148205041-62b9e13b-6204-4470-996d-613902e22d79.png">

**Comment by sarikabhimre18** [comment]
@Show-M It will display now. Change it to text.
![Screenshot (28)](https://user-images.githubusercontent.com/29194144/148206149-f86d0c90-ccc2-4260-809f-a3b049746e0c.png)

**Comment by Show-M** [comment]
@sarikabhimre18 
Can we display somehow in the way of 17:00 ? 

It does work this way for Clock range... Though what we need for this tracker is single clock.


Example: 
https://web.weave.io/979f5778-3250-430d-84f1-a774cf5425a3/admin/home
Tracker: activity-other
<img width="1368" alt="スクリーンショット 2022-01-05 12 15 27" src="https://user-images.githubusercontent.com/61481039/148209002-46caf9d4-93cb-4ac6-b351-6f17e287640c.png">

**Comment by sarikabhimre18** [comment]
@rgagne Added a display as metric for clock-single. But having issue can you please write a refine requirement for clock-single ?. As we are storing value in decimal and when display it converting decimalToTime. Which may impact on charting stuff. As we are getting decimal value on chart. So please let me know about it. Mark this fixed created a please separate ticket for it. 
https://github.com/weaveio/client.root/pull/312

**Comment by sarikabhimre18** [comment]
@Show-M Can you check this in latest build. @rgagne is that changes are live ?

**Comment by Show-M** [comment]
This will fix also "tracker: hospital".
