### ISSUE TITLE
PRF-export prints 2 same graphs and cut 1 graph in half

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#269]
Can you kindly have a look?
<img width="1002" alt="スクリーンショット 2022-01-18 11 58 35" src="https://user-images.githubusercontent.com/61481039/149924756-690009c7-b96b-48d4-a42f-87edcaff43e0.png">

sample:
[export sample.zip](https://github.com/weaveio/woll-forum/files/7888453/export.sample.zip)

**Comment by sarikabhimre18** [comment]
@Show-M unable to reproduce a issue to multiple graph print twicly can you please share a some steps for reproduce it ?.

@rgagne We are using react-print in which ref a entire screen content and based on that it will print a content. we can't change format of content display i mean specific content with print components. Please review and let me know if able to reproduce twicly print a content.

**Comment by Show-M** [comment]
@sarikabhimre18 
Step is just clicking the print-button... 
[Uploading step.zip…]()

**Comment by sarikabhimre18** [comment]
@Show-M you mean it will print double content ?

**Comment by Show-M** [comment]
@sarikabhimre18   I understand that we need to wait for Rob.

Meanwhile, my point here is that each set of graph should not be cut in half due to page-change.

With yours, this graph is cut in half. 
<img width="1390" alt="スクリーンショット 2022-01-20 12 28 55" src="https://user-images.githubusercontent.com/61481039/150330515-d20270d2-dbdb-4e35-81ea-d355cd99fa6a.png">


With mine, this graph is cut in half.
<img width="1383" alt="スクリーンショット 2022-01-20 12 29 56" src="https://user-images.githubusercontent.com/61481039/150330756-ad53baa2-f9db-418a-8304-92bdd2ffeade.png">

**Comment by sarikabhimre18** [comment]
@Show-M Okay got the point.
Thank you !

**Comment by rgagne** [comment]
@sarikabhimre18 - not clear what feedback you need; what do you suggest as a fix? 

For example we could add page breaks to the report definition that doesn't show in the screen but does when printed.

**Comment by sarikabhimre18** [comment]
@rgagne Here is the PR with react-to-print allow page breaking with it.https://github.com/weaveio/client.root/pull/338. Also with pdfmake we still get charting width issue col-6 mention in chart. Also htmltopdfmake doesn't parse our html code properly which not able to load content if render any other html it will work fine. 

But i'm not why we want to used pdf make ?

**Comment by sarikabhimre18** [comment]
@rgagne Can you please review the latest changes and let me know if have any changes. or also let me know if you have any idea to reload the all the c3 charts while printing for resizing it for col-6.

**Comment by rgagne** [comment]
@sarikabhimre18 can you send the output to @Show-M and check with him... if he is happy then will publish

**Comment by sarikabhimre18** [comment]
@Show-M Can you please review the below attached pdf ?.It's a current scenario. Please review and let me know if you want any changes.
[currentOutput.pdf](https://github.com/weaveio/woll-forum/files/8012459/currentOutput.pdf)

**Comment by Show-M** [comment]
@sarikabhimre18 
I will need Dr feedback. But it seems ok from my side.
Can you implement?

**Comment by sarikabhimre18** [comment]
@Show-M yeah just need to live a functionality it Can you check with @rgagne  ?

**Comment by Show-M** [comment]
So, as Sarika mentioned, can you make it live?  @rgagne 

there might be modification RQs later from Drs. But that is smth they can tell after some trials.

**Comment by rgagne** [comment]
it is already live
