### ISSUE TITLE
Change dot color in scatter graph according to values.strength on tracker: attack

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#274]
## Material
org: https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c
tracker: attack
layout: d0dcbd5a-dab2-4dfb-9f58-068ad4dfb9ff
graph: 発作の頻度

## Goal
- Depending on the values.strength, dots color change. 
- Dr can recognize easily if attack strength is small(1) / medium(2) / big(3)

## Possibility of color change
We can choose one of 3 below. I think 3rd is the easiest for us? 
1. Instead of color, dots change their shape: `small(1)  is △/ medium(2) is ○ / big(3) is ◎`
2. Color change as  `small(1) is blue / medium(2) is green / big(3) is red`
3.  Color change as  `small(1) is light blue / medium(2) is blue / big(3) is deep blue`

### example of 3 take from Eating disorder heatmap
<img width="1438" alt="スクリーンショット 2022-01-19 14 50 12" src="https://user-images.githubusercontent.com/61481039/150146175-cec658b7-a1c0-4558-a0c7-3d64bb891ed5.png">

**Comment by sarikabhimre18** [comment]
@Show-M We can support either points 2 or 3 and currently supported points 2 you can change the color layout based on need.
![Screenshot (77)](https://user-images.githubusercontent.com/29194144/151118565-677ed5c8-4a9b-4e12-adf0-f1215f73b265.png)

![Screenshot (78)](https://user-images.githubusercontent.com/29194144/151118793-5ac54f92-e654-4869-b7e7-84cacda8ebcc.png)


please review this in latest build.
