### ISSUE TITLE
Why does graph display nothing?

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#276]
<img width="1418" alt="スクリーンショット 2022-01-24 12 58 04" src="https://user-images.githubusercontent.com/61481039/150779114-5f17028d-f590-4ac4-85ff-0160c4e6a7b0.png">

## Goal
I want this graph display properly...

## Material
org: https://web.weave.io/634f007d-8fdf-45e4-b3a0-6d3a61cf04f5/page-search/patient-graph/p2
layout: cc0430c7-037b-4360-8edb-8a42846da3a5

I have 8 data entered already.
<img width="1168" alt="スクリーンショット 2022-01-24 13 00 29" src="https://user-images.githubusercontent.com/61481039/150779367-011f2607-9931-46f3-88b8-bdd7a3f42832.png">

**Comment by Show-M** [comment]
@sarikabhimre18 
This one should be super quick one...so awaiting :)

**Comment by sarikabhimre18** [comment]
@Show-M there data is display as you mention in above you have an 8 data but `given user [$user], given tracker [copd-diary, cat, exact, emergency-med,  regular-med, medicine-check, research-questionnaire, weight] from today to -30 days` this query return only 2 data and we mean the result so only one data point here and it's steps chart so we need more data to test.

Also please when you assigned a stuff please added to sarika project[To do] as keep eyes on board always so.
Thank you Sho !

**Comment by Show-M** [comment]
@sarikabhimre18 
Makes sense. Thank you!

And noted!
