### ISSUE TITLE
2022 January New medicine data 

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#278]
File download link: https://drive.google.com/file/d/1U2ZdOyAQirBiYzdy47vx9nRIU-sHHLkV/view?usp=sharing
* Please visit with your fluxweave account.
Please convert the data and implement to here.
<img width="1414" alt="スクリーンショット 2022-01-27 21 37 01" src="https://user-images.githubusercontent.com/61481039/151439622-6558ca8f-794b-40f6-979e-8073f27edd42.png">

**Comment by sarikabhimre18** [comment]
@Show-M Can you please review this latest generation data. And let me know if have any changes. As processing this steps https://github.com/weaveio/woll-forum/issues/120.

https://weave-io-files.s3.amazonaws.com/files/org/b15ea97f-754b-4c7f-8e8a-d8ea778385d0/gYj0ZuQt3WcyugKe9EtVShaOQjAUxF64babc9d493907c98e1791f9b0beb5c3/xml19_dosageChange.json

**Comment by Show-M** [comment]
@sarikabhimre18 
good to be copy & paste to. Let me know when its done :)

**Comment by sarikabhimre18** [comment]
@Show-M It's done !
