### ISSUE TITLE
Improvement of MEDICINE INFO - TEST

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#280]
## Basic info
org: https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c
layout: d0dcbd5a-dab2-4dfb-9f58-068ad4dfb9ff
previous ticket: #248 

## Material
Tracker: med
unit: name of medicine(name1/2/3/4/5/6)
Y axis: mg(milligram), metric: amount1/2/3/4/5/6
X axis: duration, dispatch creation data
Data range: 1 year

**Please be aware that units can be max 6 at the same time. Every time users make new entries, each medicine name can be different or same

### Example data
Sample user: Show-M
id | displayName | when | trackerName | data-amount1 | data-amount2 | data-amount3 | data-name1 | data-name2 | data-name3 | data-number
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
e416a588-0b7b-4a4b-a4bf-8bce648bef52 | Show-M | 2022-01-19 | medicine | 10 | 22 |   | ビムパット | ラミクタール |   | 2
1704a95b-bb48-4ad3-bbfc-8e2c7e4e091c | Show-M | 2021-12-09 | medicine | 50 | 8 |   | ビムパット | ラミクタール |   | 2
7a8793e8-652a-4858-a9a5-99b1a3e02778 | Show-M | 2021-10-20 | medicine | 20 | 100 | 1000 | ビムパット | イーケプラ | フィコンパ | 3

## How it looks currently
<img width="1432" alt="スクリーンショット 2022-02-03 11 41 47" src="https://user-images.githubusercontent.com/61481039/152327341-573bc6a3-d45b-4031-849e-84f6fd25ed5c.png">

### how it should look
<img width="1062" alt="スクリーンショット 2022-02-03 11 41 12" src="https://user-images.githubusercontent.com/61481039/152327236-3ad4a1e1-8ac3-41ab-981a-d36506d08dd3.png">

**Comment by Show-M** [comment]
@sarikabhimre18 
Let me know .

**Comment by sarikabhimre18** [comment]
@rgagne As per previous conversion we grouped a data based on names. Show a different name as legend and show a data based on points. If you have any idea can you please let me know some steps for point the data based on y axis ?

**Comment by rgagne** [comment]
I don't understand what the question is. 

1. If grouping by names is correct.. why does the legend need to show something different?
2. The range from Sho looks logarithmic

**Comment by sarikabhimre18** [comment]
@rgagne The questions below:-
-) Here sho request is to showing a different point in graph with one legends. I mean if name 1 has amount1 and amount2 then two steps in charts[y axis]. will not sure how can be supported a those amounts[amount1/2/3/4/5/6] in single legend with different points. Do you have any idea ?

**Comment by rgagne** [comment]
still don't understand the question

each data line should be one group of data with one label in the legend

**Comment by sarikabhimre18** [comment]
@rgagne 
Current configuration:-
```
{
          "tile": "chartSparse",
          "title": "Medicine info - Test Another",
          "display": {
            "span": "12",
            "dSpan": 6
          },
          "chart": {
            "timeSeries": "YYYY-MM; YYYY-MM-DD; P1M",
            "title": "medicine",
            "groupBy": "name1, name2, name3, name4, name5, name6",
            "dropConnectNull": true,
            "c3": {
              "data.type": "step",
              "size.height": 200,
              "axis.y.show": true,
              "axis.x.tick.format": "%Y-%b",
              "grid.x.show": false,
              "xxxcolor.pattern": [
                "#1e90ff"
              ]
            }
          },
          "connect": [
            {
              "title": "Medicine for 12 month",
              "source": "all-year",
              "trackerHandle": "med",
              "pick": "values.amount1",
              "format": "0,0",
              "tableData": {
                "id": 0
              }
            },
             {
              "title": "Medicine for 12 month",
              "source": "all-year",
              "trackerHandle": "med",
              "pick": "values.amount2",
              "format": "0,0",
              "tableData": {
                "id": 0
              }
            },
            {
              "title": "Medicine for 12 month",
              "source": "all-year",
              "trackerHandle": "med",
              "pick": "values.amount3",
              "format": "0,0",
              "tableData": {
                "id": 0
              }
            }
          ]
        }
```
Data we are using this one
### Example data
Sample user: Show-M
id | displayName | when | trackerName | data-amount1 | data-amount2 | data-amount3 | data-name1 | data-name2 | data-name3 | data-number
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
e416a588-0b7b-4a4b-a4bf-8bce648bef52 | Show-M | 2022-01-19 | medicine | 10 | 22 |   | ビムパット | ラミクタール |   | 2
1704a95b-bb48-4ad3-bbfc-8e2c7e4e091c | Show-M | 2021-12-09 | medicine | 50 | 8 |   | ビムパット | ラミクタール |   | 2
7a8793e8-652a-4858-a9a5-99b1a3e02778 | Show-M | 2021-10-20 | medicine | 20 | 100 | 1000 | ビムパット | イーケプラ | フィコンパ | 3

**Comment by rgagne** [comment]
@Show-M why is the tracker mixing the same type of data in each entry? That's definitely not a best practice.. meaning name1, value1, name2, value2, etc. If more than one is needed there should be one entry per data point. Is it necessary to combine these? What if there are 2 entries or 5 entries per day?

Possible fixes
1. Make it so the user makes one entry per medicine
2. Make a script that splits each entry automatically
3. Make a new entry form that creates multiple dispatches

What is the user flow?

**Comment by Show-M** [comment]
@rgagne 
> why is the tracker mixing the same type of data in each entry? That's definitely not a best practice.. meaning name1, value1, name2, value2, etc. If more than one is needed there should be one entry per data point. Is it necessary to combine these?

I considered the tracker as a note to submit current medicines data users are taking. Basically on each entry, users are updating/rewriting their medicine data.  Though, I understand your point completely.
I did not use "medicine layout" like asthma because on epilepsy there are only 12 meds.


> What if there are 2 entries or 5 entries per day?

That is not how it's designed. Meaning,  users create a new entry only they changed their medicine/dosage with consultation  by Dr. 


> What is the user flow?
1. Dr and User have consultations to decide what medicine and how much ml they are going to take.
2. After consultation, users go to the app and make record of medicines.
3. Users check if they forget details of meds they need to take.
4. once per few month, Dr and user have meetings. They talk if medicines have been working, etc...and they may continue using previously prescribed meds or make changes if necessary.

**Comment by sarikabhimre18** [comment]
@rgagne 
Questions:-
-) So as per discussion we need to rollback the changes of chart level grouping ?.
-) Is the currently connection level grouping supported ?. If yes then any reference of it ?. If no then we need to add configuration in connect like we did for rule in markupTable ?.

**Comment by rgagne** [comment]
@Show-M - let's review on the call; if we need to compare name1 with name2... basically we can't the way it is structured. Very likely we cannot chart what you want to chart based on the current data structure.

@sarikabhimre18 - it does not look like group by is working properly. Not sure if it did previously.

**Comment by Show-M** [comment]
@rgagne 
So, what shall we do with this? It looks like we need a different approach? 

I understood that  ideally we should have tracker for each medicine(Total 12). I guess if we can make it look as if everything is done on 1 page(layout) with 1 pop-up(tracker), it might be fine though. 

For example, we make a layout to display dropdown with all the medicine name. Then each medicine name is connected to appropriate tracker. And we retrive the latest dispatch whenever users re-open the page(layout).

Something similar to this, 
<img width="869" alt="スクリーンショット 2022-02-08 12 09 50" src="https://user-images.githubusercontent.com/61481039/152975602-6a431df3-2166-4611-a664-1e55fe4f8385.png">

**Comment by sarikabhimre18** [comment]
@rgagne This is also related with this one https://github.com/weaveio/woll-forum/issues/265. one we need date range for each medicine that mean grouped data for medicine like what we want here.

**Comment by sarikabhimre18** [comment]
@Show-M Read through all the above comment. there is mess lost the the actual requirement here can you please let me know about actual requirements for this one ?

**Comment by sarikabhimre18** [comment]
@rgagne Figuring out for it but still need some more details. We want it support fully new feature ?. Can you please let me know about some steps for start point ?.

@Show-M Can you generate a mockup with describe data point of chart for requirement clearing ?. Here we want some thing like this med1 = amount1,med2 = amount2,med3 = amount3 ?

**Comment by Show-M** [comment]
@rgagne  
I think it is better to have a talk on this? Caz it seems that i have to think a better way to collect data on this?

**Comment by rgagne** [comment]
@sarikabhimre18, @Show-M  - the main issue here is that storing the same data in different attributes prevents it from being graphed. The options are:

1. It is stored one medicine per tracker
2. It is stored the way it is now but split by a script into several data points via a script (making 1 dispatch into 2-3)
3. We add a new data source kind that calls a script and gets back JSON data (using the features we just added for PDF reports)

First see if there is a way to do it via option 1. Option 2 could work with minimal change but you then have to keep the split up dispatches in sync with the first dispatch. Option 3 is the most work but could help with other charts.

In general the same data point should always go to the same place. Putting it sometimes in attribute1, sometimes in attribute2, etc. makes the data "messy".

**Comment by sarikabhimre18** [comment]
@Show-M SO it look like we need to migrate the tracker data structure for first one ?

**Comment by sarikabhimre18** [comment]
@Show-M so for this one we can go with the first one ?. Is the data migration is proceed by you ?

**Comment by Show-M** [comment]
we can by reusing the `layout: medicine-note-2` from [Asthma org](https://web.weave.io/8e63fc1d-5dcf-42cc-8eef-84af6464a9a2/admin/layouts)

Only the big change is that we user dropdown instead of Search bar. 
This is because we have very few medicine data(only `name`)
``
ビムパット
イーケプラ
フィコンパ
ラミクタール
デパケン(セレニカ)
エクセグラン
マイスタン
トピナ
ガバペン
アレビアチン
フェノバール
ランドセン(リボトリール)
``

Does it make sense to you @sarikabhimre18  ?
<img width="1107" alt="スクリーンショット 2022-03-01 11 28 23" src="https://user-images.githubusercontent.com/61481039/156152426-03346f22-5cd6-46c5-bcd0-0b1049a043a8.png">

**Comment by sarikabhimre18** [comment]
@Show-M make sense. So I will change created another ticket for that changes.

**Comment by Show-M** [comment]
new ticket: #307

**Comment by Show-M** [comment]
I think now ticket:280 has been implemented, we can work on this ticket. Let me know if you need something!

**Comment by sarikabhimre18** [comment]
@Show-M I lost the actual request on this one can you please create an another ticket ?.
Is this an actual request https://github.com/weaveio/woll-forum/issues/280#issue-1122922934 ?

**Comment by Show-M** [comment]
@sarikabhimre18 
 It looks lie #306 is not merged yet.  Does it affect how we store data? I dont think search bar OR dropdown are important at this point?

And https://github.com/weaveio/woll-forum/issues/307 is done as i see?

If both are yes, Then sure I can create a new ticket based on the latest structure.

**Comment by sarikabhimre18** [comment]
@Show-M the latest changes is not merged with master one

**Comment by Show-M** [comment]
@sarikabhimre18 
as we had a change for how-to store data, I  updated and created a new ticket as #323.
