### ISSUE TITLE
When i open the tracker, it is fixed and not possible to control

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#281]
<img width="1421" alt="スクリーンショット 2022-02-03 18 11 36" src="https://user-images.githubusercontent.com/61481039/152393405-3fbf9d17-d8d6-4f0b-b10d-60fd5887dddc.png">
<img width="610" alt="スクリーンショット 2022-02-03 18 11 47" src="https://user-images.githubusercontent.com/61481039/152393426-9c7749e7-92f2-4f5f-9bc5-0c925309f800.png">

**Comment by sarikabhimre18** [comment]
@Show-M Here missing an configuration. We need to set a default value currently set current time of user.Please review and let me know if have any changes.
