### ISSUE TITLE
How can I display and connect value properly for `rating` ? 

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#292]
org: https://web.weave.io/922fe56d-dca5-4f83-a352-dcf5ef3b7e56/admin/trackers
tracker:  evaluation
Matrix: score

## Issue
Currently each face is connected as below. Plus as you can see, space among faces is not equal...
      "fal fa-dizzy"  - 0
      "fal fa-frown" - 1
      "fal fa-meh" - 2
      "fal fa-grin" - 3
      "fal fa-grin-beam" -100
<img width="602" alt="スクリーンショット 2022-02-15 17 36 27" src="https://user-images.githubusercontent.com/61481039/154107294-d56492e8-4a9f-473a-92d2-585e64ac7bd0.png">

## solution
Please connect each face to following values. plus display them with equal spacing.
      "fal fa-dizzy"  - 0
      "fal fa-frown" - 25
      "fal fa-meh" - 50
      "fal fa-grin" - 75
      "fal fa-grin-beam" -100

## Dr comment 
自己評価の顔入力では3段階ですが五段階にしていただけますでしょうか。

**Comment by Show-M** [comment]
@sarikabhimre18 
This one is a priority.

**Comment by sarikabhimre18** [comment]
Note for me:-
Documenting all rating properties.

**Comment by sarikabhimre18** [comment]
@rgagne Figuring out a code as per above supported a multiple of value which increment as describe above. But why we are using icon separately here ?.As material slider supported a marks. As icon width are divided in equal width but not consistent with slide marks point.Can we supported a icon in the placed of floating label with new configuration attributes ?

**Comment by sarikabhimre18** [comment]
@Show-M Fixed the solution section but will work in progress for icon spacing

**Comment by rgagne** [comment]
@sarikabhimre18 it looks like evenly spaced except there may be some negative margin or something... be careful not to break other settings and make sure everything is documented

**Comment by sarikabhimre18** [comment]
@rgagne Fixed the spacing issue here https://github.com/weaveio/client.root/pull/384. please review and let me know if have any changes.Will work in progress for documenting

**Comment by sarikabhimre18** [comment]
@Show-M Please review in latest build !

**Comment by Show-M** [comment]
waiting for the latest build

**Comment by Show-M** [comment]
@sarikabhimre18 
Can you check if this is actually fixed?

web version: 3.0.2965
current behavior: 
[test.zip](https://github.com/weaveio/woll-forum/files/8240290/test.zip)

**Comment by rgagne** [comment]
@sarikabhimre18 please include a screen shot with the new UI... want to make sure it looks ok.

**Comment by sarikabhimre18** [comment]
@Show-M  Please check in latest build.
@rgagne 
Related PR
https://github.com/weaveio/client.root/pull/407. Please review and let me know if have any changes.
Thank you !

**Comment by Show-M** [comment]
waiting for the latest build and merge.
