### ISSUE TITLE
Change default time to `Now + 5`

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#297]
org: https://web.weave.io/922fe56d-dca5-4f83-a352-dcf5ef3b7e56/admin/trackers
tracker: take medicine
<img width="1436" alt="スクリーンショット 2022-02-18 12 42 23" src="https://user-images.githubusercontent.com/61481039/154677395-68c7dfca-d6ab-43c7-b959-d1072a9d5241.png">

## Issue
In another org such as below it works just fine...Therefore i dont know what is wrong with this one...
<img width="1426" alt="スクリーンショット 2022-02-18 12 46 47" src="https://user-images.githubusercontent.com/61481039/154677496-a9159c88-f51f-4e45-9abd-4f1a28092761.png">

**Comment by sarikabhimre18** [comment]
@Show-M it will add the minutes to end date what you want here ?. Can please show me an scenario on woll app ?
![Screenshot - 2022-02-21T140757 161](https://user-images.githubusercontent.com/29194144/154918217-9c568bdb-9b4b-4693-8217-83bd90dbdc63.png)

**Comment by sarikabhimre18** [comment]
@Show-M it seem to be work fine. As per above image it will add minutes to the end date. Can you please share me gif or image where it will display ?

**Comment by Show-M** [comment]
@sarikabhimre18 

There is no need of image or display of results i think. Because this set-time(now+45) works when users open the tracker.
It does affect its result.

NOTE:
I just found out that this function is working fine on Web. But not working on Fluxweave  iOS and Android app.

Android: 3.0.2884
iOS:3.0.2952

**Comment by rgagne** [comment]
@sarikabhimre18 @Show-M Not really sure what the request is here. Could you please discuss and figure it out

**Comment by Show-M** [comment]
@sarikabhimre18 

Current setting is this.
<img width="1435" alt="スクリーンショット 2022-02-22 11 15 50" src="https://user-images.githubusercontent.com/61481039/155112142-4f71f177-1046-4c95-b0d2-8ace0c741935.png">

And I see this on web.
<img width="1184" alt="1" src="https://user-images.githubusercontent.com/61481039/155112650-f9b2340c-524d-4006-9dfd-9cad7519ce42.png">

But what I see on iOS is this. 
![IMG_0822](https://user-images.githubusercontent.com/61481039/155112607-b75467c0-4b14-438f-b6fb-4c308b362aad.jpg)

I assume the setting, `clock range, default` is not working on iOS fluxweave. And I would like you to check and fix if necessary.

**Comment by sarikabhimre18** [comment]
@Show-M default setting for in native app. But as you see that you click on schedule view time range. clock-range take that time instead of default.

**Comment by Show-M** [comment]
I see, Sarika. Now it makes sense to me...Thank you :)

**Comment by Show-M** [comment]
I just want to see if it is easy or difficult change. Let me know below.

Is it possible to fix `+5` to the matrix?  or it does not make sense?

i.g.
1. User taps somewhere between 13:00 and 14:00
2. clock-range take 13:00
![IMG_0825](https://user-images.githubusercontent.com/61481039/155299567-c0d67361-1420-47e5-bd18-f30508343c6d.png)
3. user tries to change starting time to 17:15.  (Ending time follows automatically)
![IMG_0826](https://user-images.githubusercontent.com/61481039/155299646-3bb21193-c620-40cc-9a66-9d0761ff1cf6.png)

4. clock-range now shows 17:15-17:20 (`+5` is fixed still)
![IMG_0827](https://user-images.githubusercontent.com/61481039/155299735-c3710d2a-45fc-4bed-8ed7-a8f481ed19fd.png)
