### ISSUE TITLE
Fix activity items based on the latest excel

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#300]
[活動項目表 - 復職支援(2022.02.10).xlsx](https://github.com/weaveio/woll-forum/files/8097037/-.2022.02.10.xlsx)

**Comment by sarikabhimre18** [comment]
@Show-M Please review this thing with latest stuff.
Current scenario:-
------------
![Screenshot - 2022-03-10T170647 602](https://user-images.githubusercontent.com/29194144/157654312-f9eb8e57-c7a6-4686-b72c-56bd151c4de1.png)

**Comment by Show-M** [comment]
@sarikabhimre18 

niceeeeee. But how can I do the change too for other trackers?

**Comment by sarikabhimre18** [comment]
@Show-M Just need to provide valid value in sort.
$data.sort = false instead of "none"

**Comment by Show-M** [comment]
`  "$data": {
    "sort": false,`
