### ISSUE TITLE
Allow to insert texts with minimal decorations on Fitbit-Integration screen

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#301]
The terms & condition format is like this below.  If we can not format the similar way to this, i am sure that Dr will ask us to make it easier to read using paragraph or capitalizing etc...

Can we improve? We need at least `<br>` & `<b>` ability....and font size change possible. 
Good example is "condition for users" section below.
<img width="1300" alt="スクリーンショット 2022-02-19 13 42 16" src="https://user-images.githubusercontent.com/61481039/154801259-7569374b-0c92-415d-8b8b-9e755d0c1a10.png">

## Word file screenshot with terms&condition
<img width="548" alt="スクリーンショット 2022-02-19 13 38 47" src="https://user-images.githubusercontent.com/61481039/154801144-a599dc72-b799-45b8-87f8-081ac31f92ac.png">

## Actual texts in word file
* Ignore the Strikethrough parts 
[Fitbit consensus text with T&C.docx](https://github.com/weaveio/woll-forum/files/8102185/Fitbit.consensus.text.with.T.C.docx)

**Comment by Show-M** [comment]
@sarikabhimre18  @rgagne 
It is directly related to Fitbit integration. So, I appreciate if you put some urgency and importance on this.

**Comment by sarikabhimre18** [comment]
@rgagne Fixed this changes here https://github.com/weaveio/client.root/pull/383. Please review and let me know if have any changes.
@Show-M Please review in latest build.

**Comment by Show-M** [comment]
waiting for the latest build
