### ISSUE TITLE
Text improvement for Fitbit integration screen

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#303]
![１](https://user-images.githubusercontent.com/61481039/154801656-b1e4e5e2-de8b-4bc2-ae13-2aff017accc2.png)
![２](https://user-images.githubusercontent.com/61481039/154801659-9483cae9-385a-4da5-b9d5-c148f459071e.png)

## Improved texts

1. 連携デバイスリスト
2. 利用可能
3. 利用中
4. 確認し追加

## Question 
I would like to set 2 different texts for green part as they seems to be able to have only 1 value.
For the first screen i just want to have "fitbit"
For  the second screen "Fitbit Term and Condition"
Can we do that?

**Comment by Show-M** [comment]
@sarikabhimre18  @rgagne 
Please know that this ticket and #301 should be solved together as both tickets are aiming for same goal.

**Comment by sarikabhimre18** [comment]
@Show-M What do you mean by second screen ?

**Comment by sarikabhimre18** [comment]
@rgagne Fixed this changes here https://github.com/weaveio/client.root/pull/383. Please review and let me know if have any changes.Also documented as needed.
@Show-M Please review in latest build.

**Comment by Show-M** [comment]
waiting for the latest build

**Comment by sarikabhimre18** [comment]
@rgagne Can you please generate a latest build for this one.
