### ISSUE TITLE
Dispatch created on mobile shortcut does not appear on Data query

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#305]
## Issue
org: https://web.weave.io/532759ed-633a-4c15-8526-79b704b1ac4c/admin/dataService
I created a following dispatch on mobile and calendar tab on web. But it is not visible on data query.  Why??

## Dispatch data created on mobile
tracker id: db3543cb-5e1e-4a8c-9014-4b1febf91fc6
dispatch id: 6a4b4c86-62dd-4069-ad61-6dd349ba05bd
![IMG_0829](https://user-images.githubusercontent.com/61481039/155976604-36266ed7-6596-4400-b9e0-5d60c127051b.png)
![IMG_0830](https://user-images.githubusercontent.com/61481039/155976607-41bd5218-fc6a-4a31-851a-90a16e8131b9.png)

## Where I can see 
![IMG_0831](https://user-images.githubusercontent.com/61481039/155976665-f9ae6e92-cf5e-4aa0-a36b-66d99d582432.png)
<img width="1435" alt="スクリーンショット 2022-02-28 12 35 19" src="https://user-images.githubusercontent.com/61481039/155976879-b2130619-4079-4d16-868a-add48cdab486.png">

### Where I cannot see
`given dispatch[6a4b4c86-62dd-4069-ad61-6dd349ba05bd]`
<img width="1434" alt="スクリーンショット 2022-02-28 12 36 19" src="https://user-images.githubusercontent.com/61481039/155976988-36ce45ac-1941-4f1f-af7f-08a33f704914.png">

`given user[sho.mitsuya.1005@gmail.com], given tracker[hospital]`
<img width="1071" alt="スクリーンショット 2022-02-28 12 46 12" src="https://user-images.githubusercontent.com/61481039/155978312-b3b41f67-3088-4424-ac0d-30102e7aef32.png">

**Comment by sarikabhimre18** [comment]
@Show-M it's a future date so you needed to provide the date range some thing like this.
![Screenshot - 2022-02-28T172544 599](https://user-images.githubusercontent.com/29194144/155979529-26888636-9c54-423a-9593-b75502bce2de.png)

**Comment by Show-M** [comment]
Future date must contain `future` in the query...
