### ISSUE TITLE
Fix time range always as `+5 min`

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#309]
I just want to see if it is easy or difficult change. Let me know below.

Is it possible to fix `+5` to the matrix? 

## Example flow
1. User taps somewhere between 13:00 and 14:00
2. clock-range take 13:00
![IMG_0825](https://user-images.githubusercontent.com/61481039/155299567-c0d67361-1420-47e5-bd18-f30508343c6d.png)
3. user tries to change starting time to 17:15.  (Ending time follows automatically)
![IMG_0826](https://user-images.githubusercontent.com/61481039/155299646-3bb21193-c620-40cc-9a66-9d0761ff1cf6.png)

4. clock-range now shows 17:15-17:20 (`+5` is fixed still)
![IMG_0827](https://user-images.githubusercontent.com/61481039/155299735-c3710d2a-45fc-4bed-8ed7-a8f481ed19fd.png)

**Comment by sarikabhimre18** [comment]
@Show-M Here not sure about actual request. Are you mean removing the +5 ?

**Comment by rgagne** [comment]
@Show-M before getting detailed about the UX, can you explain what problem we're trying to solve?

**Comment by Show-M** [comment]
Here is the brief of Dr comment I got. 
I told him that as the following "solution" might not be possible as it is used in other researches. 

## Problem 
By tapping schedule  and choosing `tracker: take-medicine` always give 1h time range on default. 
(as this is how it is designed in the layout)
![sample 1](https://user-images.githubusercontent.com/61481039/156564810-3f12f77d-dab7-4d14-99fa-023477b685b0.gif)

Usually patients takes no more than 5min to take medicine. 
Therefore it must be troublesome for them to change time range to 5min everytime.

## Solution
Fix time range as ` +5min`. 
This will give always +5min whenever users change starting time(ending time follows automatically and dis play as ` Starting time |  (Starting time + 5min) = ending time`
<img width="440" alt="スクリーンショット 2022-03-03 13 29 28" src="https://user-images.githubusercontent.com/61481039/156565141-3120a661-a163-46e9-b217-e75c88ee3fee.png">

**Comment by sarikabhimre18** [comment]
@Show-M So verify:-
Here request is to add +5 min instead of 1 hour in time right ?

**Comment by Show-M** [comment]
@sarikabhimre18 
Basically 2 RQ here. 
1. fix time range as `+ 5min` when Patients open up `tracker:take-medicine`
2. When patients move `starting time` on the image above, `ending time` gets set automatically as "starting time + 5min"

But first, i would like to clarify
1. if this change makes sense 
2. if this change is worth to do

**Comment by sarikabhimre18** [comment]
@rgagne Here is the latest changes https://github.com/weaveio/client.root/pull/414. Please review and let me know if have any changes.

@Show-M Please review this in latest build.

**Comment by Show-M** [comment]
waiting for its latest build
