### ISSUE TITLE
Delete Shortcut on fitbit integration screen

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#318]
org: https://web.weave.io/922fe56d-dca5-4f83-a352-dcf5ef3b7e56/admin/navigations
How to access:
![1](https://user-images.githubusercontent.com/61481039/158219962-98826aa0-6fe0-4149-a18e-73f0aa312f30.png)

2 Locations:
<img width="856" alt="スクリーンショット 2022-03-14 17 37 38" src="https://user-images.githubusercontent.com/61481039/158219408-0fd2ed08-7a0e-49dd-b73c-4e6004fe0751.png">
<img width="829" alt="スクリーンショット 2022-03-14 17 37 44" src="https://user-images.githubusercontent.com/61481039/158219433-52099688-bd18-4dbf-894f-81a7a44c6ae3.png">

## Solution 
Please delete shortcut button from these screen. 
<br>
**Do not delete from other pages such as calendar**
<br>
I thought that i can delete by using `context`...but i could not find out where to add it.
![2](https://user-images.githubusercontent.com/61481039/158219975-42799bef-d261-4c35-b825-99083fc6f33d.png)
![3](https://user-images.githubusercontent.com/61481039/158219981-29395ec2-2ea2-41a7-92ee-bf5d2ad600be.png)

**Comment by sarikabhimre18** [comment]
@Show-M Fixed this issue please review and let me know if have any changes. 
We Just need to changes in navigation options configuration.
![Screenshot - 2022-03-15T111716 070](https://user-images.githubusercontent.com/29194144/158315040-38b541d7-4bde-427a-bdd6-31faca7501b2.png)
