### ISSUE TITLE
Add `action-sheet` tracker to wizard besides current tracker

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#321]
org: https://web.weave.io/8e63fc1d-5dcf-42cc-8eef-84af6464a9a2/admin/org
tracker:  action-sheet
location: image
<img width="1175" alt="スクリーンショット 2022-03-17 17 37 29" src="https://user-images.githubusercontent.com/61481039/158849615-b3789dd2-7b17-442a-86ce-264a99b972d0.png">

## issue
It looks like wizard is allowed to have only 1 tracker 

## Solution
Please allow wizard to have more than 1 tracker

**Comment by sarikabhimre18** [comment]
@rgagne Supported a this thing here https://github.com/weaveio/client.root/pull/411. Please review and let me know if have any changes.

@Show-M Please review this in latest build.

**Comment by sarikabhimre18** [comment]
@rgagne Here is the latest version change PR https://github.com/weaveio/client.root/pull/419. Can you please review and let me know if have any changes.

**Comment by sarikabhimre18** [comment]
Note for me:-
Change here http://localhost:3000/8e63fc1d-5dcf-42cc-8eef-84af6464a9a2/admin/org When merged with master one.

**Comment by Show-M** [comment]
<img width="710" alt="スクリーンショット 2022-04-04 19 55 14" src="https://user-images.githubusercontent.com/61481039/161529696-09619b42-44d3-4e6f-87b1-dad1e6768dcb.png">
