### ISSUE TITLE
User attribute and loading issue

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#327]
Fluxweave iOS: ver 3.0.2969
- The trackers, height and intake do not appear. 
- The screen freezes as `saving....`
[ios sample.mp4.zip](https://github.com/weaveio/woll-forum/files/8439548/ios.sample.mp4.zip)

Fluxweave desktop: ver. 30.0.2985
- Height tracker appears 2 times.  It should be just 1 time.
[desktop sample.zip](https://github.com/weaveio/woll-forum/files/8439582/desktop.sample.zip)

**Comment by Show-M** [comment]
This one is important. If you can solve it before 10th, I appreciate..

**Comment by rgagne** [comment]
@Show-M -- mobile -- this is because supporting multiple trackers is a new feature; latest version works properly

**Comment by sarikabhimre18** [comment]
```
{
  "week": "monday",
  "wizard": {
    "version": 2,
    "intake": {
      "trackers": [
        "e71aafe8-f8f5-4beb-a51a-c7f8fe09680a"
      ]
    },
    "edit": {
      "trackers": [
        "e71aafe8-f8f5-4beb-a51a-c7f8fe09680a",
        "897a2470-c6d9-47d1-ac1a-380976455278"
      ]
    }
  }
}
```

**Comment by rgagne** [comment]
@Show-M @sarikabhimre18 - intake and edit run at different times. However with the recent changes they (incorrectly) get all mixed together. @sarikabhimre18 is fixing..

@Show-M - i think a single tracker was probably fine here (for future reference)

**Comment by sarikabhimre18** [comment]
@rgagne Here is the latest PR https://github.com/weaveio/client.root/pull/427. Please review and let me know if have any changes.
@Show-M Please review this in latest build.
Thank you !

**Comment by Show-M** [comment]
note:
edit is edit.. profile edit, intake only runs first time you open the app
