### ISSUE TITLE
Change the background color of task board to `#a4dd00`

### ISSUE THREAD

**Issue by Show-M** [weaveio/woll-forum#333]
![IMG_0886](https://user-images.githubusercontent.com/61481039/162759098-31abb783-dcd8-4c20-9998-b51e71642796.png)

**Comment by Show-M** [comment]
@sarikabhimre18 
Can you tell me where i can configure it ?

**Comment by sarikabhimre18** [comment]
@Show-M Just for your reference we can change here.
![Screenshot - 2022-04-13T115237 314](https://user-images.githubusercontent.com/29194144/163113143-6fa40caf-8d8e-4bb1-82a9-1943d1c10d4a.png)
