### ISSUE TITLE
Body area selection

### ISSUE THREAD

**Issue by shunyaogawa** [weaveio/woll-forum#63]
There was a request to show the area where the above medicine was applied or the itchy part. It was a rough idea, so
In the figure on the left, face, shoulders, chest, belly, upper arms, back of elbows, arms, hands, thighs, thighs, legs
In the middle figure, the scalp, neck, left shoulder blade, right shoulder blade, lower back, buttocks, thighs, calves, and back of the knees.
In the figure on the left, the forehead, around the eyes, left cheeks, right cheeks, nose, chin, ears
I want to make something that gives a rough area by selecting the part.
 I would like to have you make something like the figure and create something that you can select by tapping.

Sorry for the late reply.
![画像2](https://user-images.githubusercontent.com/78076746/109742693-de8d7480-7c12-11eb-9495-41bad75e6ec8.jpg)
![画像１](https://user-images.githubusercontent.com/78076746/109742735-f107ae00-7c12-11eb-8c6e-aa1c1a3c12a7.jpg)

Thank you.

　上のような薬を塗った部分、またはかゆい部分などを面積で出してほしいという要望があった。大まかでよいということだったので、
左の図では、顔、肩、胸、腹、上腕、肘裏、腕、手、太もも、もも、足
真ん中の図では、頭皮、首浦、肩甲骨左、肩甲骨右、背中下部、尻、太もも、もも、膝裏
左の図では、おでこ、目の周り、左ほほ、右ほほ、はな、あご、耳
といったように、部位を選択することにより、大まかな面積を出すというものを作りたい。
図のようなものを作っていただき、タップすると選択できるようなものを作成したいと考えている。
返信が遅れてしまい申し訳ありません。
よろしくお願いいたします。

**Comment by shunyaogawa** [comment]
At the meeting, I was asked when this feature would be available.
Can you reply when this feature can be generated?

**Comment by rgagne** [comment]
@shunyaogawa - Some questions

1. Will annotations made from web only or web / mobile?
2. Should the user be able to define the areas or they would be pre-defined (see video for examples)

See:
https://weave-io-files.s3.amazonaws.com/files/org/8e63fc1d-5dcf-42cc-8eef-84af6464a9a2/QHeGbZvf3vLlqOBdrXUm7MY3JFWatXeb33c2a49e13d136b0a7081f7c4286ad/React-App.webm

Thank you

**Comment by shunyaogawa** [comment]
Thank you for your reply.
I'm thinking of creating it for use with Mobile's tracker.
Regarding another question, I couldn't see the video from the URL, so I couldn't judge what kind of question it was.

**Comment by Show-M** [comment]
@shunyaogawa 
Try this. This is an actual video, so it should work.
[画面収録 2021-04-06 21.59.33.zip](https://github.com/weaveio/forum/files/6264771/2021-04-06.21.59.33.zip)

**Comment by shunyaogawa** [comment]
Thank you for your reply.
I was able to see the video.
I was thinking of using it on my mobile phone, so I was thinking of selecting the part that I traced with my finger.
If it is either of the two, please select the specified area.

**Comment by shunyaogawa** [comment]
I have a meeting soon, can you tell me when this feature will be complete?

**Comment by shunyaogawa** [comment]
I'm sorry to ask you many times. Can you tell me when it will be completed and how far it is currently going?

**Comment by rgagne** [comment]
This is a fairly large feature request.

Please see specification: https://github.com/weaveio/forum/issues/122 and provide comments.

**Comment by rgagne** [comment]
@shunyaogawa this is now ready per #122 ; @sarikabhimre18 can help you with configuration

docs are here https://docs.fluxweave.com/Configuration/Trackers/Capture/ImageAnnotation/
